### ISSUE TITLE
キーボードとコントローラーの同時入力が出来ない

### ISSUE THREAD

**Issue by c-stella** [exch-bms2/beatoraja#106]
Konami公式のIIDX専コン（プレミアムコントローラー）の場合、スクラッチが少し特殊（INFINITASの仕様に合わせられている）なので、スクラッチ操作をキーボードのLshiftとLctrlにコンバートして使用しないとまともにプレイできないのですが（lr2ではそのようにプレイしていました）
どうやらbeatorajaでは曲開始時に使った機器しかプレイ中は認識しないようで（コントローラーで開始すればコントローラー、キーボードで開始すればキーボードだけ）、特殊な環境の場合プレイできないようです。

**Comment by exch-bms2** [comment]
See #101.
