### ISSUE TITLE
Crash when second running

### ISSUE THREAD

**Issue by humekuru** [exch-bms2/beatoraja#111]
Download, and unzip. 

1.Run beatoraja-config.bat
2.Not push 'run', close the (configuration)window.
3.Retry to run. It may Crash. 

Only for first running.  Sorry for poor English.

**Comment by LNTakeshi** [comment]
It was fixed in #104.
It has not been released yet, but it has been fixed in beatoraja 0.5.2.
If you want to try it immediately, you can build beatoraja yourself.
http://excln.hatenablog.com/entry/2017/09/03/194753

**Comment by humekuru** [comment]
understand. Sorry become a repetition.
