### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by N-ISOGE** [exch-bms2/beatoraja#12]
Looks like a problem with LN.

[unknown.zip](https://github.com/exch-bms2/beatoraja/files/691879/unknown.zip)

**Comment by exch-bms2** [comment]
I think this was caused by conflicting of two thread for loading bms, and may be fixed on 0.3.7.

**Comment by N-ISOGE** [comment]
the Problem still exists

https://youtu.be/tNmH5AdwtHw

**Comment by N-ISOGE** [comment]
Bug fixed
