### ISSUE TITLE
Can not use ASIO

### ISSUE THREAD

**Issue by L-SMK** [exch-bms2/beatoraja#15]
ASIO can not be used in this environment.
I guess that it does not correspond to ASIO2.0 Driver.

(ASIOが当環境にて使用することが出来ません。)
(ASIO2.0に対応していないのではないかと推測します。)

OS : Windows10 Pro x64
CPU : i7-4790
RAM : 24GB
Graphics : GTX 1050ti
Sound : STRIX RAID PRO

**Comment by exch-bms2** [comment]
In the latest master build, ASIO driver will be replaced with PortAudio-based. If you try it and still fail, reopen this issue.
