### ISSUE TITLE
collenction of PC configuration that PortAudio can't use

### ISSUE THREAD

**Issue by exch-bms2** [exch-bms2/beatoraja#158]
If you can't select PortAudio, please comment your PC hardware/software configurations and error log.
PortAudioを選択できない場合、PCのハード/ソフト構成とエラーログをコメントして下さい

**Comment by negi4894** [comment]
My computer configurations.
Hardware
Motherboard: ASUS P5Q deluxe P45 chipset
CPU: Intel Core2Quad Q9550 OC 3.63GHz
Mem: hynix PC2-6400 2GB * 4
Storage
    OS: ADATA SX900 240GB
    beatoraja installed: WD 10EZEX 1TB
GPU: GeForce GTS 450
Soundcard: soundmax onboard
Controller: DJ DAO RealEditionDouble

Software
OS: Windows 7 Ultimate x64 [Version 6.1.7601]
Java: java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Audio driver: ASIO4All v2

Error log
<log>
<record>
  <date>2018-01-28T01:15:00</date>
  <millis>1517069700509</millis>
  <sequence>0</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>bms.player.beatoraja.launcher.PlayConfigurationView</class>
  <method>updateAudioDriver</method>
  <thread>13</thread>
  <message>PortAudioは選択できません : D:\BMS\beatoraja\jportaudio_x64.dll: Can't find dependent libraries</message>
</record>
<record>
  <date>2018-01-28T01:15:02</date>
  <millis>1517069702650</millis>
  <sequence>1</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>bms.player.beatoraja.launcher.PlayConfigurationView</class>
  <method>updateAudioDriver</method>
  <thread>13</thread>
  <message>PortAudioは選択できません : Could not initialize class com.portaudio.PortAudio</message>
</record>
<record>
  <date>2018-01-28T01:15:05</date>
  <millis>1517069705210</millis>
  <sequence>2</sequence>
  <logger>global</logger>
  <level>SEVERE</level>
  <class>bms.player.beatoraja.launcher.PlayConfigurationView</class>
  <method>updateAudioDriver</method>
  <thread>13</thread>
  <message>PortAudioは選択できません : Could not initialize class com.portaudio.PortAudio</message>
</record>
</log>

That's all.
If you need more information, Please talk to me.

Best regards,

**Comment by negi4894** [comment]
I could select PortAudio if I was update Java version to 1.8.0_161-b12.
