### ISSUE TITLE
Game is not working

### ISSUE THREAD

**Issue by Thanh9356** [exch-bms2/beatoraja#171]
When I open it, it isn't work, I open it again and again. The last open, my PC is dump

**Comment by parataxia** [comment]
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

make sure you get the `Windows x64` Java setup file and install it, then try running the game again from the `beatoraja-config.bat` .

**Comment by exch-bms2** [comment]
We can't help you unless you disclose your PC environment, which file you opened and what your PC dumped.
