### ISSUE TITLE
[MacOS] Any key input aren't accepted

### ISSUE THREAD

**Issue by bz9s** [exch-bms2/beatoraja#2]
I have no problem with config window, but application stops responding after booting main game. I can't input on a keyboard at main game window.
It doesn't seem to be completely freezing because the bottom right clock works normally.
Is there any help? I tried on macOS 10.11.6

**Comment by exch-bms2** [comment]
This ploblem is difficult to be solved because of conflicting between JavaFX and libGDX.
If using beatoraja 0.2.1, you can boot without configuration window by making dummy file 'song.db'.
And if you want to boot configuration window, please use command line:
> java -jar beatoraja.jar -c

**Comment by bz9s** [comment]
OK, I tried creating an empty file named 'song.db' and put on the same directory as jar file, but I could not skip config window.
When I booted by terminal, I got lots of exception in JavaFX application thread.
In any case, it seems I can't avoid freezing main game window.

**Comment by exch-bms2** [comment]
Please try it:

1. boot configuration window
2. select 'リソース' tab, and add bms/bmson directory path to BMS Path
3. Push '楽曲全更新' button
4. Exit configuraion window and reboot

**Comment by bz9s** [comment]
Oh, I can do well on version 0.1.2. When using 0.2.1, only configuration window is displayed again.

**Comment by exch-bms2** [comment]
Now I released 0.3 and fix this bug.

**Comment by bz9s** [comment]
works correctly. Thank you :-)
