### ISSUE TITLE
issue with jkoc play

### ISSUE THREAD

**Issue by ghost** [exch-bms2/beatoraja#21]
Using a JKOC + USB adapter, can get it to map fine but while playing if I press a key it gets translated to tt key action, and happens after the button is done being pressed (i.e: eventUp).. so basically every key gets echo'd to tt key and happens after the fact of pressing the key. btw, it seems to work on the 1st song, then while playing it the bug appears.

hope to hear soon in possible solution...

*edit & update*

so I did some random investigation and actually got it to work. the issue seems to be related to the x/y axis of the joystick which when used with a JKOC + USB Adapter. when a key is pressed on my JKOC besides the actual TT keycode I believe the x/y axis is modified as well, which creates a bug to make the TT activated from given code of how the axis is handled.. the fix for now is to simply go to your controller settings in Windows ("Set up USB Game Controllers" or some such) and click proper joystick. then click "Reset to Default", followed by "Properties". The "Z Axis" and "Z Rotation" rainbow graph  needs to be 50%/50% otherwise it knocks the x/y axis off whilst playing beatoraja, and the only method I know to fix it is to randomly meddle with the settings in "Calibrate" till the Z Axis/rotation is 50/50%.

I might fix it later if i find enough time.. should be simple enough to perhaps implement a JKOC controller mode or a more transparent solution.

**Comment by parataxis** [comment]
Would anyone have a clue as to why my JKOC TT when alternating rapidly and rotating the turntable refuses to render a bomb on the TT lane ? perhaps on JKOC controllers (I think I've heard of this) you basically need a filter to get this to work. didn't notice this until using desout2.

**Comment by Agrrox** [comment]
i think this issue is resolved?
