### ISSUE TITLE
Practice Mode :  CONSTANT is not functioning

### ISSUE THREAD

**Issue by MiraiScarlet** [exch-bms2/beatoraja#258]
(ENG for google)
BPM is a changing song, constant option is not available in practice mode.

(JP)
BPMが変化する曲において、プラクティスモードをCONSTANTオプションを付けてプレイしてもCONSTANTが有効になりませんでした。

Win10
ビルド版、Release0.5.4.1にて確認

**Comment by exch-bms2** [comment]
It is in the specifications. Some of assist options are disabled in practice mode. If you want this feature, need to discuss about the selection of practice options.
