### ISSUE TITLE
ARM and OpenGL ES support

### ISSUE THREAD

**Issue by cjfh** [exch-bms2/beatoraja#29]
To make beatoraja run on ARM devices like the [ODROID C2](http://www.hardkernel.com/main/products/prdt_info.php?g_code=G145457216438) or the [Raspberry Pi 3](https://www.raspberrypi.org/products/raspberry-pi-3-model-b/), it needs 32 bit (hard float) and 64 bit ARM libraries and OpenGL ES support.

32 bit hard float ARM libraries (libopenal, liblwjgl and libgdx) can be found here: [armhf_libs.zip](https://github.com/exch-bms2/beatoraja/files/907794/armhf_libs.zip)

**Comment by exch-bms2** [comment]
I don't have testing environments. Please implement in yourself.
