### ISSUE TITLE
Down color depth when Fullscreen started

### ISSUE THREAD

**Issue by negi4894** [exch-bms2/beatoraja#291]
Color depth forced down 32bit to 16bit(improbably, or more down) when Application started,
Unnatural gradation in the fullscreen.
If start with Borderless or Window mode, press F4 to fullscreen will not down color depth(32bit to 32bit).
but, DAO controller will not response.(start with fullscreen or... stay mode Window or Borderless can response DAO)
first, I think, my computer has poor graphic memory.
second, I was test on different computers.
third, computer spec doesn't matter.
forth, Vertical synchronization is on? -> No.
What is the problem?

I have 2 computers.
Q9550/GTS450(1GB)/mem8GB/Win7
4790K/GT970OC(4GB)/mem32GB/Win7

**Comment by exch-bms2** [comment]
posted same issue #342
