### ISSUE TITLE
Backslash key "\" doesn't work on Linux

### ISSUE THREAD

**Issue by Tearff** [exch-bms2/beatoraja#314]
I tried to use beatoraja on Linux. I pressed "6" to go to key config but I could not map the backslash key to anything. The game ignores the key completely.
On my keyboard layout it's 100% necessary for DP: `lshift zsxdcfv ,l.;/'\ rshift`.

**Comment by exch-bms2** [comment]
This is in the libGDX specification so that we can't do anything.
