### ISSUE TITLE
Problems with continuous scratch LNs

### ISSUE THREAD

**Issue by ghost** [exch-bms2/beatoraja#319]
(0.5.6d)
スクラッチレーンにLNが到達する際、スクラッチを操作したままの場合
判定タイミングにて逆方向に回しても反応せず、見逃し扱いとなってしまいます

大半の譜面では特に問題とならないのですが、
PrayStation [4_PStwo]、Doppelganger [DPH]等
短い間隔で皿LNが連続する譜面の場合、普通にプレーしても正しく処理されない為大きな問題となります

**Comment by exch-bms2** [comment]
これでは発生状況が見えないので、もう少し詳細にお願いします
・LN MODEは何ですか？
・スクラッチレーンにLNの何が到達する際？(始点？終点？)
・何の判定タイミングで逆方向に回して(LNの始点？終点？それともその後のノーツ？)、見逃し扱いのなったのは？

**Comment by Canid48296** [comment]
滅茶苦茶な文章を推敲せず載せてしまいすみません

正確に言いますと、
・LNモードはLN(CN,HCNモードでこの問題は起こりませんでした)
・スクラッチLNの始点が判定ラインに到達する直前までスクラッチを動かしている
・スクラッチLNが判定ラインに重なるときにスクラッチを逆方向に操作する
このときスクラッチLNが反応せず、見逃し扱いになってしまいます

**Comment by Canid48296** [comment]
今確認したのですが

間隔の狭い二つのスクラッチLNがあるとき、
一つ目の終点でCN,HCNのように操作すると問題なくコンボが継続し、空POORも発生しないことに気づきました

（１つ目のLN始点で左回転
　１つ目のLN終点で右回転（本来必要のない操作）
　２つ目のLN始点で左回転）

問題解決の手掛かりになれば幸いです

**Comment by exch-bms2** [comment]
修正しました。◆2のenrai等、いくつかのLN皿が連続する譜面で問題ないことを確認しています。

**Comment by Canid48296** [comment]
いつもありがとうございます。
