### ISSUE TITLE
Make horizontal scrolling notes possible

### ISSUE THREAD

**Issue by bonjorno8** [exch-bms2/beatoraja#323]
This would be for staff style lanes in 24k/48k, as well as potential future taiko mode maybe.

**Comment by SackMagiclight** [comment]
I think that it is unnecessary.
@exch-bms2  What do you think?

***
「BMSコンテンツの発展」には現段階でつながらない気がしますがどうでしょうか。

**Comment by exch-bms2** [comment]
I think "horizontal scroll" is not so much effective. 3D-scrolling is much more effective.
