### ISSUE TITLE
Random option bug

### ISSUE THREAD

**Issue by dotstart2132** [exch-bms2/beatoraja#324]
(日本語)
H-Random、AllScratch、Random+、S-Random+をかけてプレイするとリザルト画面後、選曲画面が表示されずconfigurationの画面が表示されます。このときBGMは聞こえますが選曲画面に戻ることはなく、またconfigurationはスキンタブとIRタブのみハイライトされています。
beatorajaを終了させ、起動後上記のプレイオプションをかけた譜面を選曲画面で選択した瞬間フリーズします。
どなたかこのような現象が発生した方、原因がわかる方いないでしょうか。
返信お待ちしてます。

(English)
When I select and play one of H-Random, AllScratch, Random+, S-Random+, the song selection screen is not displayed after the result screen and the configuration screen is displayed.
At this time I can listen to BGM but beatoraja does not return to the song selection screen, the configuration screen is highlighted only on the skin tab and IR tab.
I forced the beatoraja to kill and then start up and then freeze the musical score you selected on the song selection screen with the above play option applied.
Are those who experienced such a phenomenon or know the cause?
I am waiting for a reply.

**Comment by exch-bms2** [comment]
Maybe already fixed. Try latese build (not 0.5.5).
