### ISSUE TITLE
Google Chrome intercepts IPFS requests

### ISSUE THREAD

**Issue by ikaruga777** [exch-bms2/beatoraja#333]
下記環境でIPFSを使用した楽曲の展開に失敗するのを確認しました。
- beatoraja Releases/0,6
- Windows10
- java version "1.8.0_171"
- Google Chromeバージョン: 66.0.3359.181

beatorajaは、ダウンロード後の展開、配置も行ってくれるように見えますが、
所持していない曲のダウンロードリクエストがGoogle Chromeのファイルダウンロードとして処理されてしまい、正しく展開ができませんでした。

IPFSテーブルは`http://lnt.softether.net/insane.html`を指定しています。
詳細については環境を作った後でもう少し追ってみたいと思います。

**Comment by ikaruga777** [comment]
- masterをビルドして実行
- Release/0.6をビルドして実行

上記のケースではダウンロード、展開、楽曲再生まで成功しました。
開発環境を整えたことに起因するのかと考え、もう一度失敗する環境で試しましたが、やはりchromeにリクエストを横取りされてしまいました…

**Comment by LNTakeshi** [comment]
難易度表`http://lnt.softether.net/insane.html`はIPFS hashに加え、通常のダウンロードURLを全て`http://ipfs.io/～～`に置き換えています。
beatorajaでは何らかの理由でMusicDownloadProcessorが動いていないとき、IPFS hashが指定されていても通常のダウンロードURLが開かれるようになっていて、それがchromeで開かれるということに繋がっていると考えられます。

どちらが開かれているのか確認する方法として、難易度表では`http://ipfs.io/`を指定していますが、beatorajaでMusicDownloadProcessorを通した時はコンフィグで指定したゲートウェイ（デフォルトは`https://gateway.ipfs.io/`）を指定しているので、これでMusicDownloadProcessorを通してダウンロードが実行されているかどうか区別できます。もしChromeで`https://gateway.ipfs.io/`が開かれているのなら問題有り、ということです。

なお、MusicDownloadProcessorはconfigで次のチェックが入っていないと動作しません。
![image](https://user-images.githubusercontent.com/4867425/41265377-fa91c376-6e2c-11e8-8ee9-f050f69e706f.png)

問題解決にあたって次の点がどうなっているか確認してください。
- Chromeで開かれるURL
- configのチェックが入っているか
- ダウンロード時、コンソールに次のメッセージが表示されるか
![image](https://user-images.githubusercontent.com/4867425/41265612-17b2cf8a-6e2e-11e8-8d17-e3752f9b7375.png)
- コンソールに何らかのエラーが出ていないか

**Comment by ikaruga777** [comment]
詳細な解説ありがとうございます。
ご指摘の通り、チェックが外れていました。難易度表の設定等で勝手がわからず、書き換えてしまったままだったようです。

- Chromeで開かれるURL
  - 約束 -HappyHyperStarmiX- (虎の穴)を開いたとき
  - http://ipfs.io/api/v0/get?arg=QmXEjVWLaQHako9i9k3ngHC87af6GSuXSdcSiHq6z4r6H6&archive=true&compress=true
- configのチェックが入っているか
  - 入っていませんでした
- ダウンロード時、コンソールに次のメッセージが表示されるか
  - 表示されません
- コンソールに何らかのエラーが出ていないか
  - 出力されていません

大変お騒がせいたしました:pray:
