### ISSUE TITLE
v0.6 release launch script does not work on some machines

### ISSUE THREAD

**Issue by wcko87** [exch-bms2/beatoraja#336]
In the v0.6 release, the config launch script currently uses this, which does not work on all machines:
`java -Xms1g -Xmx4g -cp beatoraja.jar;ir/* bms.player.beatoraja.MainLoader`
On some machines, running this line will just show java command line options (instead of running beatoraja).

1. Inverted commas should be placed around the `beatoraja.jar;ir/*` to prevent the shell from potentially treating it as two separate lines.
2. On linux, the semicolon `;` should be changed to a colon `:`

Correct version:
- Windows:
    `java -Xms1g -Xmx4g -cp "beatoraja.jar;ir/*" bms.player.beatoraja.MainLoader`
- Linux:
    `exec java -Xms1g -Xmx4g -cp "beatoraja.jar:ir/*" bms.player.beatoraja.MainLoader`

(I'm not sure about whether `;` or `:` should be used for OSX)

Source: https://stackoverflow.com/a/219801

**Comment by exch-bms2** [comment]
Maybe fixed on 0.6.1.
