### ISSUE TITLE
beatoraja is setting a 16bit video mode (RGB565)

### ISSUE THREAD

**Issue by Tearff** [exch-bms2/beatoraja#341]
beatoraja switches to a 16bit video mode, and I can't find any option to set it to 24bit. Because of this there is very visible banding on some elements.
beatoraja 0.6, 1080p fullscreen, Windows 10

skin .tga file
![skin .tga file](https://user-images.githubusercontent.com/6359267/42385463-c087280e-8134-11e8-8528-4b182c316b51.png)

ingame screenshot
![ingame screenshot](https://user-images.githubusercontent.com/6359267/42385476-c9aacab2-8134-11e8-8b98-fa4d18fa34b1.png)

**Comment by negi4894** [comment]
I have same problem on#291
There is no answers yet.

**Comment by exch-bms2** [comment]
Maybe no contributors have occured this problem. I always play on fullscreen, works correctly.
There will be no progress until users who have occured investigate the cause of this. 
@Tearff @negi4894, do you have any ideas?

**Comment by SackMagiclight** [comment]
I also work correctly.
Since it can not be reproduced, it can not be modified either. Information is missing.

**Comment by exch-bms2** [comment]
I think this problem is caused by your PC configuration, or libGDX or LWJGL problem. You'd better to post the same issue to libGDX or LWJGL project to solve this.

**Comment by SackMagiclight** [comment]
libgdx : https://github.com/libgdx/libgdx
LWJGL : https://github.com/LWJGL/lwjgl3
