### ISSUE TITLE
Practice mode - Press 5 key to start autoplay

### ISSUE THREAD

**Issue by Agrrox** [exch-bms2/beatoraja#344]
Currently the 5 key has no use in practice mode. 5 key could be used to start autoplay. This will be great feature because it will allow player to watch and listen at lower/higher frequencies at certain parts of bms.

**Comment by wcko87** [comment]
Use number keys 1-4 in autoplay mode to speed up or slow down autoplay.

**Comment by Agrrox** [comment]
I'm asking for additional functionality in Practice mode.

**Comment by SackMagiclight** [comment]
I think that Practice mode is **not** a bms viewing mode.
(There is room for discussion.)

If you only slow/fast play a part of the music, you can do slow/fast playback in Practice mode and leave it alone.
Why are there AutoPlay reasons?

**Comment by Agrrox** [comment]
> you can do slow/fast playback in Practice mode and leave it alone.

You wont hear the sound

**Comment by SackMagiclight** [comment]
understood.
I feel like a request to use it like "ubmplay".

**Comment by Agrrox** [comment]
Autoplay does not allow to set start time and end time of playback.

**Comment by exch-bms2** [comment]
Maybe contributors think this is an useless function for most users and want to know why you want to do with the use of this function.

**Comment by Agrrox** [comment]
I want to watch autoplay from certain start-ending point at lower or higher frequencies to watch and learn key patterns. Autoplay does that but its is not convenient enough because you have to skim through the song just to see part of bms you want. It feels **intuitive for me** to use same key controls that are in music select in practice mode. What other functionality and controls beatmania have in its practice mode?


Controls in Music select:
> 1 KEY ... play
> 3 KEY ... practice
> 5 KEY ... Auto play 
> 7 KEY ... Replay (If replay log exists)

Controls in Practice mode:
> 1 KEY ... play
> 5 KEY ... Auto play 
> 7 KEY ... Replay (If replay log exists) 

Just image to explain what I meant:
![demo](https://user-images.githubusercontent.com/10901821/42990994-9d048a54-8c04-11e8-959e-08c9371d2e51.jpg)

**Comment by SackMagiclight** [comment]
>  It feels intuitive for me to use same key controls that are in music select in practice mode.

It is a very useful and interesting opinion.
I think that it will be a concept to expand to "Playable BMS viewing mode(?)" instead of Practice mode.
(It is a problem of comparison between mode name and function.)

We need to hear other contributors opinion.

***

What I was thinking was an extension of Auto Play from the command line.
ex ) `java -jar beatoraja.jar -a --start (time) --end (time) --fre (frequency rate)  [BMS path]`
Likewise, it is possible to call Practice Mode as well...?

**Comment by wcko87** [comment]
I think an autoplay feature would be good for practice mode. I like to use practice mode for testing/previewing charts I'm making too.

https://files.catbox.moe/1ok46p.mp4
https://files.catbox.moe/1d0n7n.mp4

Also, I think it is okay to continue to call it practice mode.
