### ISSUE TITLE
I don't listen any sound

### ISSUE THREAD

**Issue by haraedono** [exch-bms2/beatoraja#347]
I tried to select 'OpenAL' and 'PortAudio', but I didn't listen all sound. ex)BGM, Key sounds, Songs, etc..
I only see this cmd message.
![20180803001041](https://user-images.githubusercontent.com/20905742/43593205-2f233306-96b2-11e8-9f0f-f3dfc8f6801a.png)

How can i do?

**Comment by exch-bms2** [comment]
0.6.1 release package doesn't contain any BGM/Sound set, so that you need to prepare sound sets if you want to play BGM/Sound on Music Selector.

No sounds on playing BMS may be caused by other reason (ex. BMS file uses ADPCM).

**Comment by haraedono** [comment]
bms file work very well.
But bmson file does not work.
I don't know this reason.
