### ISSUE TITLE
The select and play (coffee) artwork in the default skin could use an update

### ISSUE THREAD

**Issue by Xerxius** [exch-bms2/beatoraja#377]
I found the _current_ coffee themed backgrounds uninspiring, so I made some images that could replace them.

**Select screen:**
![artsyselect](https://user-images.githubusercontent.com/44162026/47285463-4ff09d80-d5eb-11e8-8c8b-f4610e69996e.png)
![select](https://user-images.githubusercontent.com/44162026/47285467-5121ca80-d5eb-11e8-8f20-e4919101e62b.png)
**Play screen:**
![artsyplay](https://user-images.githubusercontent.com/44162026/47285462-4f580700-d5eb-11e8-8322-7aecd3dc825a.png)
![play](https://user-images.githubusercontent.com/44162026/47285466-50893400-d5eb-11e8-80b9-b049b47ca63d.png)

Some generic mixer table and dj art seemed appropriate for a music game.

**Comment by SackMagiclight** [comment]
@Xerxius 
I think that it is very good.
"beatoraja" is the coined term of "beat" + "toraja".
It might be fun to have coffee elements somewhere.

**Comment by Xerxius** [comment]
I made some coffee themed lane covers, so the coffee styling won't dissapear completely if my background suggestions replace the current backgrounds

![heartcoffee](https://user-images.githubusercontent.com/44162026/47293237-dc11bd80-d609-11e8-9547-da34ec73ea18.png)
![steamycoffee](https://user-images.githubusercontent.com/44162026/47293239-dc11bd80-d609-11e8-9fdd-b0548486b66d.png)
![darkcoffee](https://user-images.githubusercontent.com/44162026/47293236-db792700-d609-11e8-8a3d-5750dfa43fdf.png)
![lightcoffee](https://user-images.githubusercontent.com/44162026/47293238-dc11bd80-d609-11e8-99e3-c165319ba6a9.png)

**Comment by SackMagiclight** [comment]
@exch-bms2 個人的には良い案かなと思いますがどうでしょう？

**Comment by exch-bms2** [comment]
Now these images are included in default skins. Thanks!
