### ISSUE TITLE
Practice Mode: multiple bugs at lower freqency play

### ISSUE THREAD

**Issue by Agrrox** [exch-bms2/beatoraja#39]
Issues:
- LongNotes are invisible during play 
- LongNotes are visible and become invisible after press
- key animation become stuck after pressing LongNote
- key become stuck after pressing LongNote making unable to register key press

also there is Grammatical error in Practice mode options: 
Right now it is _Freqency_, it should be _Frequency_.

**Comment by exch-bms2** [comment]
fixed on 0.4.1.
