### ISSUE TITLE
Missing beatoraja.jar file?

### ISSUE THREAD

**Issue by nebbii** [exch-bms2/beatoraja#397]
I've downloaded the releases and cloned the repository, but I cannot find the beatoraja.jar file to boot it with. Is it intentionally missing? I can't figure out how to run the game.

**Comment by aixxe** [comment]
The release page has a [link to a pre-compiled version](https://mocha-repository.info/download.php).

To compile from source, running `ant create_run_jar` will create a beatoraja.jar file in the build directory.

**Comment by nebbii** [comment]
Thanks, this clears things up
