### ISSUE TITLE
a proposal for improve

### ISSUE THREAD

**Issue by N-ISOGE** [exch-bms2/beatoraja#4]
- Storing the value of a judgment ms value with a score to the server, and then using the value to determine Cheat.
- Display a dispersion of the value (variance, standard deviation) and The average of the absolute value in the results screen.

**Comment by exch-bms2** [comment]
1.A system of determining cheat can't be realized only client side, So it needs to work with chroma-IR developer.
2.Can you show me a sample image? (Layout, etc)

**Comment by TSHN** [comment]
- i mean storing the - + ms value of all notes or to store the mean and standard deviation of the absolute value of the ms value and to display it in the play results

- i think 
![20161113_141422](https://cloud.githubusercontent.com/assets/7279031/20243891/dc4649ac-a9af-11e6-852a-1a617e1030f4.png) is good  


- 物理的に、またコントローラを通じて不正行為をするのが容易に判別するためにすべてのノート-+msの値を保存したり、そのms値の絶対値の平均値と標準偏差を保存してプレー結果に表示

**Comment by exch-bms2** [comment]
need to discuss on wiki.
