### ISSUE TITLE
Preview song?

### ISSUE THREAD

**Issue by Reyder95** [exch-bms2/beatoraja#400]
Not sure if there is possibility of song previewing while in song select but I can't hear any songs so it would be a nice feature.

(not sure if there is a discord or place to ask questions, sorry if there is)

**Comment by SackMagiclight** [comment]
`#PREVIEW` ?

https://github.com/exch-bms2/beatoraja/wiki/%E6%A5%BD%E6%9B%B2%E8%A3%BD%E4%BD%9C%E8%80%85%E5%90%91%E3%81%91%E8%B3%87%E6%96%99#bms%E6%8B%A1%E5%BC%B5%E5%AE%9A%E7%BE%A9

**Comment by exch-bms2** [comment]
BMS:

#PREVIEW (preview music audio file path)

BMSON:

"preview_music" : "(preview music audio file path)" (on "info" object)

**Comment by MikiraSora** [comment]
Does beatoraja will automatic find `preview*.ogg` if .bms filenot define `#PREVIEW`?

**Comment by SackMagiclight** [comment]
@MikiraSora yes
-> https://github.com/exch-bms2/beatoraja/issues/400#issuecomment-453907642

> #PREVIEW (音源ファイルパス)
選曲時に対象の楽曲バーにカーソルを合わせることで自動演奏されるプレビュー音源を指定します。 指定されていない場合、フォルダ内にあるpreview(*).wav(ogg)をプレビュー音源として自動指定します。

If you want to add a preview to an existing BMS, simply place `preview(*).wav(ogg)` in the folder and it will work.

**Comment by MikiraSora** [comment]
> @MikiraSora yes
> -> [#400 (comment)](https://github.com/exch-bms2/beatoraja/issues/400#issuecomment-453907642)
> 
> > #PREVIEW (音源ファイルパス)
> > 選曲時に対象の楽曲バーにカーソルを合わせることで自動演奏されるプレビュー音源を指定します。 指定されていない場合、フォルダ内にあるpreview(*).wav(ogg)をプレビュー音源として自動指定します。
> 
> If you want to add a preview to an existing BMS, simply place `preview(*).wav(ogg)` in the folder and it will work.

yep I made a preview audio generator tool for non-preview charts.
But I found that **preview not work** until Beatoraja **rebuild database**.
I dont know it's bug or just a limitation.

**Comment by SackMagiclight** [comment]
As you know, The preview path is recorded when BMS is read into the DB, so it is necessary to update the DB.
The easiest way is to add the value to the preview column in the DB in your own program.
