### ISSUE TITLE
As a DP player, we need auto-scratch option

### ISSUE THREAD

**Issue by RIVERSTAR2190** [exch-bms2/beatoraja#401]
Thanks to your carefulness, we have DP options like flip and battle.
As you know, DP players sometimes play DBM (double battle mirror) or DBR (double battle random)
for increase their abilities.
But because we play 2 SP charts by 2 hands, we can't play properly without auto-scratch options.
(as a DP 10dan player, I set DBM play as assist-easy, 2p mirror, and 'scratch-auto' in IIDX.)
I want you to add auto-scratch option and on/off switch to make scratch note visible or invisible.

Thanks for your effort to make next generation bms player.

**Comment by SackMagiclight** [comment]
Play Option -> DP Option -> [BATTLE AS]
This one?

![image](https://user-images.githubusercontent.com/20876249/51098639-1fe22080-180f-11e9-9fe9-9c717f8d6f88.png)

**Comment by RIVERSTAR2190** [comment]
oh I didn't know that. Thanks. I'll close this one.
