### ISSUE TITLE
Sound level issues from beatoraja 0.6.5 onward

### ISSUE THREAD

**Issue by wcko87** [exch-bms2/beatoraja#403]
There seems to be a problem with the sound levels in beatoraja versions 0.6.5, 0.6.6 and 0.6.7.
0.6.4 and below are ok.

Comparison video:
beatoraja 0.6.4 https://www.youtube.com/watch?v=dzKCp14zNBs

beatoraja 0.6.6 https://www.youtube.com/watch?v=u5PTNTUt5H0

Recorded using portaudio, but the same thing happens for OpenAL.
(bug not discovered by me)

**Comment by exch-bms2** [comment]
fixed on latest version
