### ISSUE TITLE
ArrayIndexOutOfBoundsException in adding songs.

### ISSUE THREAD

**Issue by sig-ume** [exch-bms2/beatoraja#427]
In adding songs, output error like image.
![スクリーンショット 2019-03-24 00 15 01](https://user-images.githubusercontent.com/10582244/54867931-e6f39880-4dc9-11e9-9a59-97c3ffff24c1.png)

**Comment by wcko87** [comment]
I think it will be nice to find out which song causes the crash.

@exch-bms2 I think if BMSDecoder crashes, beatoraja should not stop song loading.
I think it is better to catch the exception and continue loading other songs.
(and log the exception + report which song folder fails to load)
What do you think?

**Comment by exch-bms2** [comment]
Obsolete issue.
