### ISSUE TITLE
issue with input not registering notes in-game

### ISSUE THREAD

**Issue by parataxia** [exch-bms2/beatoraja#43]
I can play with the latest release binary build (0.4.1 as of now), but if I compile from source and play the latest build the game (Play screen) does not register notes, even though the lanes activate as they should etc. Constant "poors."... I can provide video if that helps.

**Comment by parataxia** [comment]
Looks like it is a bug in **"play/JudgeManager.java"** with "Authentic style" not working, probably due to refactorization of this code...

**Comment by exch-bms2** [comment]
Could you tell me this BMSON mode_hint?

**Comment by exch-bms2** [comment]
No replies, may be solved and close.
