### ISSUE TITLE
Occasional crashes just before the result screen (using skin)

### ISSUE THREAD

**Issue by terry422** [exch-bms2/beatoraja#438]
The application stalls just before the result screen:
<pre>4월 30, 2019 3:13:48 오후 bms.player.beatoraja.skin.lr2.LR2SkinCSVLoader getSourceImage
경고: IMAGEが定義されてないか、?み?みに失敗しています : #SRC_IMAGE,0,21,0,0,-1,-1,1,1,0,0,0,0,0,,,,,,,,
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at bms.player.beatoraja.MainState.setSkin(Unknown Source)
        at bms.player.beatoraja.MainState.loadSkin(Unknown Source)
        at bms.player.beatoraja.result.MusicResult.create(Unknown Source)
        at bms.player.beatoraja.MainController.changeState(Unknown Source)
        at bms.player.beatoraja.play.BMSPlayer.render(Unknown Source)
        at bms.player.beatoraja.MainController.render(Unknown Source)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:233)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)</pre>

Java version is:
<pre>java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)</pre>

I am currently using LITONE5 1.1.0 ( http://desout2.freeiz.com/litone5-oraja-1.0.html ), beatoraja 0.7.0, Windows 10 (Korean).

Probably caused by `skin.lr2.LR2SkinCSVLoader.getSourceImage()` returning null:
https://github.com/exch-bms2/beatoraja/blob/cbde6d4fc6b34faf8b0169517d0192ef7745ad10/src/bms/player/beatoraja/skin/lr2/LR2SkinCSVLoader.java#L966-L967

Two things to note:
1) I have been experiencing this bug before beatoraja 0.7.0, so the new version did not introduced the bug.
2) The behavior is inconsistent; sometimes the result screen appears normally, but at other times the exception is thrown.

Is there anyone experiencing the same problem?

**Comment by wcko87** [comment]
If you are on Korean locale, this may be a locale issue.
LITONE5 is known to have issues if you are not on JP locale. (due to japanese folder names, and japanese option names in the csv files)

If the cause is indeed the locale, there are two possible solutions:
1. switch to JP locale
2. run beatoraja with the UTF-8 flag (instructions here: https://github.com/exch-bms2/beatoraja/issues/360#issuecomment-466765784)

Please let us know if this is indeed a locale issue.

**Comment by terry422** [comment]
Adding -Dfile.encoding="UTF-8" to _JAVA_OPTIONS seems to be working.
I have tested several times, and so far, crash before the result screen did not occur(though, I experienced a crash by access violation, but not sure if this crash was caused by changing the option).
Will close this issue after testing for a few days.

**Comment by wcko87** [comment]
I believe the crash by EXCEPTION_ACCESS_VIOLATION (0xc0000005) is a separate issue.
From what I've gathered so far, that crash happens with the .mp4 video background in LITONE5 when you restart a song too quickly.
Disabling video backgrounds seems to fix that crash for now. I'm currently still trying to figure out how to fix that crash.

**Comment by terry422** [comment]
Tested enough to see that the crash is not occurring anymore.
Closing the issue.
