### ISSUE TITLE
[Mocha] MPEG BGA is not played in multiple destinations

### ISSUE THREAD

**Issue by excln** [exch-bms2/beatoraja#441]
Version: 0.7 (Mocha-Repository version only)
Example case: Halcyon [DP ANOTHER] / Default 14key skin

When the playing skin has multiple BGA destinations, an MPEG BGA is not played correctly but shown like a still image. The reason may be version difference in FFmpeg because that occurs only in Mocha-Repository version.

**Comment by kasakon555** [comment]
Version: 0.7.0
Example case1: マツユキソウ [DP Another] / Default 14key skin & LITONE5
Example case2: lapis / Default 14key skin & LITONE5

同じような現象になったので報告します。
BGAが複数されていた所を1つにしたところ表示されることを確認。
画像形式のBGAは問題なし。

![20190516_042732_Play_LEVEL11 マツユキソウ  DP Another](https://user-images.githubusercontent.com/4884630/57804455-a6931400-7795-11e9-800d-088fbba34f7b.png)

![20190516_045239_Play_LEVEL11 マツユキソウ  DP Another](https://user-images.githubusercontent.com/4884630/57804806-8152d580-7796-11e9-9bcf-3a2815ec8109.png)


![20190516_043415_Play_LEVEL10 Lapis  14keys Another](https://user-images.githubusercontent.com/4884630/57804557-e823bf00-7795-11e9-9090-9ed9569e7992.png)
