### ISSUE TITLE
Pressing F11 opens wrong page when using MinIR as a primary IR

### ISSUE THREAD

**Issue by RbDrache** [exch-bms2/beatoraja#442]
It currently opens:
https://www.gaftalk.com/minir/viewer/?songhash=Songhash&lnmode=0

But MinIR uses this format now:
https://www.gaftalk.com/minir/#/viewer/song/Songhash/0

**Comment by SackMagiclight** [comment]
@RbDrache 
Please download latest jar API file (from "Download API"、Updated on April 30, 2019)
https://www.gaftalk.com/minir/#/

Please comment on issues related to MinIR with [twitter](https://twitter.com/sack_magiclight) or Discord (BMS Server Japan : beatoraja chanel : 海岸砂丘(Sack Magiclight)#6651) .


@exch-bms2 お時間ある時で構いませんので、同梱APIの更新をお願いします。
