### ISSUE TITLE
[MacOS] .app laucher for beatoraja

### ISSUE THREAD

**Issue by Agrrox** [exch-bms2/beatoraja#452]
Hello, here is a convenient .app file that uses bash script to launch beatoraja. I hope it will be included with beatoraja distribution in the future. Let me know what you think.

### Instalation: 
drag and drop into beatoraja/beatoraja.jar

### .app folder contains these scripts:

**beatoraja.app/Contents/Info.plist**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>launcher</string>
	<key>CFBundleIconFile</key>
	<string>application.icns</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0.0</string>
	<key>CFBundleSignature</key>
	<string>xmmd</string>
	<key>CFBundleVersion</key>
	<string>1.0.0</string>
	<key>NSAppleScriptEnabled</key>
	<string>NO</string>
</dict>
</plist>
```

**beatoraja.app/Contents/MacOS/launcher**
```
#!/bin/sh

# Set the working directory
DIR=$(cd "$(dirname "$0")"; pwd)

# Run the application
exec "$DIR/launchscript" $DIR
```

**beatoraja.app/Contents/MacOS/launchscript**
```
#!/bin/sh

DIR=$1
ICON="$DIR/../Resources/GenericApp.icns"
DIR="$DIR/../../../"
APP_JAR="beatoraja.jar"
APP_NAME="beatoraja"

cd "$DIR"
java -Xdock:name="$APP_NAME" -Xdock:icon="$ICON" -Dsun.java2d.opengl=true -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -cp "$DIR;.;" -jar "$DIR/$APP_JAR"
```

**Comment by Agrrox** [comment]
update:
script should not bypass the built-in system security "Gatekeeper"

For example if you open beatoraja.jar you will see this window
![popup window](https://user-images.githubusercontent.com/10901821/61297818-51976c80-a7dd-11e9-9b2e-ac61355ed8a3.png)
![gatekeeper](https://user-images.githubusercontent.com/10901821/61297819-51976c80-a7dd-11e9-9dc1-61fd6484c61e.png)

**Comment by phu54321** [comment]
Hello, could you upload a .zip containing an .app?
