### ISSUE TITLE
A tree-structured folder is no longer loaded

### ISSUE THREAD

**Issue by yantaisa11** [exch-bms2/beatoraja#453]
以前は読み込んでくれましたが、最近のバージョンになってからBMS Pathを親フォルダに設定してある中がツリー構造になっているフォルダが読み込まれなくなってしまっています。曲検索からは選曲できますが曲フォルダからは選べない状態です。
(It was loaded before, but recently folders with tree structure in BMS Path set as parent folder are not loaded anymore. You can select songs from the song search but not from the song folder.)

Version used 0.7.0

例:BMSPath（BMS¥BMS Event）
![screenshot 34](https://user-images.githubusercontent.com/47597055/58276019-605f3580-7dd1-11e9-9e8a-4df78ee4b3d7.png)
![20190524_030258_Music_Select](https://user-images.githubusercontent.com/47597055/58276053-70771500-7dd1-11e9-9c96-bde2d8c279f3.png)

**Comment by exch-bms2** [comment]
I couldn't reproduce the problem. Maybe caused by your songdata.db and config.json file.

Can you send your song data.db and config.json?

**Comment by yantaisa11** [comment]
As data was uploaded collectively, please confirm.
https://www.dropbox.com/s/r4la6mvbee8x3ws/deta.zip?dl=0

**Comment by exch-bms2** [comment]
This is caused by problems with processing relative path directory (maybe 0.6.6~), and now fixed this issue.

Please remove download links (These data have some personal information)

**Comment by yantaisa11** [comment]
Thank you for the correction. The link has been deleted.
