### ISSUE TITLE
How do we adjust the volume on beatoroja?

### ISSUE THREAD

**Issue by tontonziru** [exch-bms2/beatoraja#46]
How do we adjust the volume on beatoroja?
（どうやってbeatoroja内で音量を調節しますか？）

**Comment by exch-bms2** [comment]
You can change system, key, background volume in the latest build. If you want to change this in 0.4.1, need to edit config.json directly.

**Comment by tontonziru** [comment]
Volume does not appear in the config on my pc.
Do I need to set something, or is it a problem?
（私のパソコンのコンフィグ画面ではボリュームが出ていません。設定が必要なのでしょうか、または不具合ですか？）

![20170606120338](https://user-images.githubusercontent.com/29162920/27002823-d48386ec-4e25-11e7-90b5-0dc9acf8a7be.png)
![20170610 214122](https://user-images.githubusercontent.com/29162920/27002825-da9e8c3e-4e25-11e7-916d-33fd30d56556.jpg)

**Comment by Agrrox** [comment]
I think you are using latest release which does not have this option. You need to compile from current source code to have that option.
