### ISSUE TITLE
Ubuntu: Could not load bms.player.beatoraja.MainLoader

### ISSUE THREAD

**Issue by nebbii** [exch-bms2/beatoraja#467]
I'm trying to run beatoraja on Ubuntu 18.10 using OpenJDK 8 with Openjfx installed, but i'm still getting a missing class error.

```
***@***:~/Documents/beatoraja$ java -jar beatoraja.jar \[6yen\]cynic/
Error: Could not find or load main class bms.player.beatoraja.MainLoader
```

```
***@***:~/Documents/beatoraja$ ./beatoraja-config.command 
Picked up _JAVA_OPTIONS: -Dsun.java2d.opengl=true -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
Error: Could not find or load main class bms.player.beatoraja.MainLoader
```
This happens with both the releases and compiled directly from source. I've tried running the jar file from the build folder with the same results, does it need to have certain folders next to it?

**Comment by SnappyGithub** [comment]
it looks like you dont have javafx installed, i tried it and it worked for me, you need to enter in the terminal: `sudo apt-get install openjfx`.

**Comment by q09029** [comment]
The same phenomenon occurs in Ubuntu 18.04 after install openjfx.
and i resolve it.

enter in the terminal.

apt purge openjfx
apt install openjfx=8u161-b12-1ubuntu2 libopenjfx-jni=8u161-b12-1ubuntu2 libopenjfx-java=8u161-b12-1ubuntu2
apt-mark hold openjfx libopenjfx-jni libopenjfx-java

**Comment by nebbii** [comment]
That fixed it @q09029, thank you. I had the regular openjfx installed but it didnt work
