### ISSUE TITLE
#DEFEXRANK judge behavior

### ISSUE THREAD

**Issue by Deipnosophy** [exch-bms2/beatoraja#468]
`#DEFEXRANK` has priority over `#RANK` according to https://github.com/exch-bms2/beatoraja/blob/master/manual/extension.txt#L44-L47. I think this is a bit of a problem for some songs:

- https://venue.bmssearch.net/bmsshuin2/99 uses `#DEFEXRANK 400` which turns the chart into expand judge
- http://manbow.nothing.sh/event/event.cgi?action=More_def&num=115&event=110 uses `#DEFexRANK 120`, which is close to `VERY EASY` but sets `#RANK 3` which is `EASY`.

I suggest only using `#DEFEXRANK` if there is no `#RANK` set or restricting it to bmson charts. Alternatively, only use `#DEFEXRANK` to set one of the hard/normal/easy/very easy judges and increase the threshold for `VERY EASY` to a value higher than 120.

Thank you for your consideration!

**Comment by exch-bms2** [comment]
These songs seem to define #DEFEXRANK on purpose, so I think this behaviour is acceptable.
If ignoring #DEFEXRANK with #RANK definition, may cause a problem on other songs defining #DEFEXRANK. 
How do you think about it?

**Comment by Deipnosophy** [comment]
I think `#DEFEXRANK 400` is fine since the value is so high it has to be done on purpose (and someone commented about it: https://venue.bmssearch.net/bmsshuin2/99)

For older charts that use `#DEFEXRANK 120`, I think there is an inconsistency in that other clients treat 100 as being `#RANK 2`, where Beatoraja treats 100 as `#RANK 3` (based on https://hitkey.nekokan.dyndns.info/cmds.htm#DEFEXRANK). I don't think there is a good solution to this.

**Comment by Deipnosophy** [comment]
Does anyone else have any thoughts on this? I'd like Beatoraja to treat `#DEFEXRANK 120` as `#RANK 2`, which should match the behavior of other clients according to the BMS command memo page:

`The initial value of a judgment is specified at percentage. The value 100 corresponds to #RANK 2 (label: NORMAL).`
