### ISSUE TITLE
I want the ability to random select song in the selected category.

### ISSUE THREAD

**Issue by miyabi-398** [exch-bms2/beatoraja#469]
難易度表/レベル/楽曲選択の時に
プレイする楽曲をランダムにセレクトする機能があったらいいなと思いました。

**Comment by exch-bms2** [comment]
「目をつぶってスクロールして決定」に対して優位性が欲しいです。

**Comment by SackMagiclight** [comment]
"目をつぶってスクロールして決定" だと未所持楽曲に当たりますね
所持している楽曲（getPath != null) な楽曲をランダム選曲できれば良さそうです。

**Comment by SackMagiclight** [comment]
現状の作りだと新しいselectBarが要るかもですね（Not songBar な選曲できるBar)

**Comment by exch-bms2** [comment]
未所持楽曲にあたったときは大人しく楽曲導入するか
「未所持楽曲を楽曲バーとして表示しない」オプション」を追加すればいいと思います。

このあたりの機能追加の工数は結構大きいので(スキン、描画周りも変更が必要)、
例えばフォルダ内楽曲を連続シャッフルプレイとか、もっと拡張性のある要素が
欲しいと考えています。

miyabi-398さんの意見をもう少し詳細に聞きたいところです。

**Comment by miyabi-398** [comment]
技術的な部分詳しくはないですが、フォルダや難易度表を選択したときに曲のリストがあると思うのでその先頭に”？？？”という曲を挿入し、それ選んだらリストの中からランダムに選曲できればできるかなとかぐらいに思っていました。

将来性についてですが、思いつくのだと・・
・ランセレ使って配信盛り上げる
・コースランダム
・ノンストップモード
とかでしょうか。
