### ISSUE TITLE
Some BMS do not sound (beatoraja 0.7.3)

### ISSUE THREAD

**Issue by yantaisa11** [exch-bms2/beatoraja#473]
違法なBMSの対策の強化が関わってきてると思われますが0.7.3にしてからogg音源などのADPCMを使われていないBMSにも関わらず音が鳴らないBMSがいくつか発生しています。
例：BOFU2017の[Garakuta Doll Play](http://manbow.nothing.sh/event/event.cgi?action=More_def&num=117&event=116)

BMSファイルが.wavで定義されているのにもかかわらず音源がoggになっているなど音源と定義が異なっていると鳴らなくなるのを確認したのでそれが原因かもしれません

**Comment by exch-bms2** [comment]
再生不可BMSの対応はこちらで行います:

https://docs.google.com/spreadsheets/d/1YF_C12POQxhFR_eX36zWhEQqrRvhu-3uB73Yjq6F2Fg/edit?usp=sharing

**Comment by yantaisa11** [comment]
確認した再生不可のBMSを全て載せるときりがないので２つほど書いてきましたがBMSファイル内で定義されている音源の拡張子と実際の音源の拡張子が違うBMSは全て音が鳴らない状態でした
音源を定義されている拡張子に書き換えると鳴ります
