### ISSUE TITLE
The volume of ogg key sounds of specific BMS is low

### ISSUE THREAD

**Issue by Shimi9999** [exch-bms2/beatoraja#474]
キー音がoggのBMSの特定のキー音の音量が非常に小さくなってしまいます。

例:
- [エピトゥリカの祀](http://manbow.nothing.sh/event/event.cgi?action=More_def&num=130&event=54) : bass01.ogg
- [Absurd Gaff](http://manbow.nothing.sh/event/event.cgi?action=More_def&num=11&event=54) : noize01.ogg
- [スピカ](https://event.yaruki0.net/VSevent/impression/13) : vocal1.ogg
- [Peach boy john](http://manbow.nothing.sh/event/event.cgi?action=More_def&num=78&event=115) : Vocal BGM_000.ogg

問題のあるキー音は、oggからwavに変換すると正常な音量で再生されます。
OpenAlでのみ発生します。PortAudioでは発生しません。(Peach boy johnは常に発生)
batから起動すると発生します。jarから直接起動すると発生しません。(Peach boy johnは常に発生)

0.7.2, 0.7.3での発生を確認しました。

**Comment by exch-bms2** [comment]
こちらにお願いします:

https://docs.google.com/spreadsheets/d/1YF_C12POQxhFR_eX36zWhEQqrRvhu-3uB73Yjq6F2Fg/edit?usp=sharing
