### ISSUE TITLE
Specific BGAs do not play

### ISSUE THREAD

**Issue by Shimi9999** [exch-bms2/beatoraja#475]
以下のBMSのBGAが正常に再生されません。
- [Bosh](http://manbow.nothing.sh/event/event.cgi?action=More_def&num=7&event=115)
- [Allie Stars](http://manbow.nothing.sh/event/event.cgi?action=More_def&num=131&event=123)
- [うきせいこう feat.西川寅吉](http://manbow.nothing.sh/event/event.cgi?action=More_def&num=229&event=123)

選曲1回目では、BGAは真っ黒で表示されます。連続して再度選曲すると、BGAの最初のシーンが静止画で表示されます。

たまに正常に再生されることがありますが、再度選曲すると正常に再生されなくなります。

0.7.2, 0.7.3での発生を確認しました。

**Comment by exch-bms2** [comment]
こちらにお願いします:

https://docs.google.com/spreadsheets/d/1YF_C12POQxhFR_eX36zWhEQqrRvhu-3uB73Yjq6F2Fg/edit?usp=sharing
