### ISSUE TITLE
Error dialogs popping under main window

### ISSUE THREAD

**Issue by Gluestick** [exch-bms2/beatoraja#479]
The game was freezing everytime I attempted to start it. Turns out there was this error message hidden underneath the main window. I only found out about this, because I accidentally dragged the main window before starting at one point.

![image](https://user-images.githubusercontent.com/3269145/66719450-3ba34300-edf0-11e9-8fbb-c7a4966ff9bb.png)

### Expected behavior
This (and other?) error dialogs should pop-up over the main window.

**Comment by exch-bms2** [comment]
Do you understand why this error message appears?
