### ISSUE TITLE
Feature request: Way to adjust keysounds/bgm volume separately while playing

### ISSUE THREAD

**Issue by wtre** [exch-bms2/beatoraja#482]
This is a feature some traditional bms players have. (ruv-it fully supports an in-game control, lr2 partially supports them on music select screen)
It's very helpful for examining chart design, or checking timing with ear.
For now, turning the entire game on and off for every single adjustment is a hassle.

An ideal goal could be a set of seperate in-game silder. For example:

- tap-tap-hold START and control keysounds volume with turntable, vice versa via SELECT for bgm.
- numpad 1/3 to decrease/increase keysounds volume and 2 to toggle, 4/6 and 5 for bgm.

However, a simpler solution (i.e. 2 separate toggle key to on/off keysounds or bgm, in practice mode) would also be granted.

**Comment by doneara** [comment]
lr2 and beatoraja can do on play screen by defining a skin.
