### ISSUE TITLE
"Illegal BMS Files" error indescriptive, unhelpful at best as well as erroneous.

### ISSUE THREAD

**Issue by Leuphorie** [exch-bms2/beatoraja#487]
In my ~400+ GB BMS collection I have not a single illegal BMS file. After manually verifying everything and refactoring my own folders and rebuilding my BMS database overnight I am greeted with the same error. 

"This Application detects 8 illegal BMS songs. Remove them, update song database and restart."

Again, I do not have any illegal BMS songs. It would be helpful to:

1) remove this error or fix its error margin
or
2) actually list what "illegal BMS songs" the user might have.

Thank you
![image](https://user-images.githubusercontent.com/6729134/68867099-954fa380-06f5-11ea-9d57-49c93750ed25.png)

**Comment by Leuphorie** [comment]
Attached is my BMS folder structure.
[folder structure.txt](https://github.com/exch-bms2/beatoraja/files/3847237/folder.structure.txt)
 There are no illegal BMS songs here.

@exch-bms2 Please take a look.

**Comment by exch-bms2** [comment]
Please send your songdata.db file.

**Comment by Leuphorie** [comment]
Here is a link to download my songdata.db file.

https://mega.nz/#!RdRRACDR!0PGYQFquCsl20S2wcBmdKCCQtYDCvffExT3HDBBVwgk

**Comment by exch-bms2** [comment]
There are no illegal BMSes on your songdata.db, so I could start beatoraja correctly with your db file.
Maybe you removed illegal BMSes while refactoring folders, but your songdata.db still have some illegal BMSes and beatoraja detected these BMSes when starting configuration window.

Please retry, maybe starts correctly.
And Please Don't get/have illegal BMS files (especially 2dx hacks)

**Comment by Leuphorie** [comment]
I do not have any illegal BMSes and have never had any illegal BMSes. The songdata.db I sent you is the songdata.db I have right now, and I am unable to start beatoraja with it. I have tried to rebuild my song db once again and I am still facing the same issue.

**Comment by SackMagiclight** [comment]
I downloaded 0.7.4 and started it once.
Next, overwritten songdata.db.
Then started beatoraja.
It worked without problems.

**Comment by Leuphorie** [comment]
> I downloaded 0.7.4 and started it once.
> Next, overwritten songdata.db.
> Then started beatoraja.
> It worked without problems.

I am unable to start it even once.

**Comment by SackMagiclight** [comment]
hmm...

Download, start bat, and immediately press the launch button.
At that time, do not set the BMS path.
Do not reuse the old folder. (For problem isolation.)
Overwriting beatoraja.jar may cause unintended behavior.
If you get the above error even though you have n’t set a song, I ’m not sure ...

**Comment by Leuphorie** [comment]
> hmm...
> 
> Download, start bat, and immediately press the launch button.
> At that time, do not set the BMS path.
> Do not reuse the old folder. (For problem isolation.)
> Overwriting beatoraja.jar may cause unintended behavior.
> If you get the above error even though you have n’t set a song, I ’m not sure ...

Thank you for your reply. I tried this and it did not work. It seems the problem is within the software.

**Comment by exch-bms2** [comment]
Do you mean that illegal BMSes are detected in spite of no song loaded?

**Comment by Leuphorie** [comment]
> Do you mean that illegal BMSes are detected in spite of no song loaded?

I mean that illegal BMSes are detected in spite of having no illegal BMSes like you can see in my songdata.db

**Comment by exch-bms2** [comment]
Hmm. Maybe this issue depends on your environment (locale, OS, etc...)

I think this problem is caused by SQLite processing on your environment.
Here is a test build (beatoraja.jar file).
https://mocha-repository.info/download/debug/beatoraja_test.zip
Download, overwrite with it and run beatoraja-config.bat, and immidiatly press exit button (don't reload songs. )
After that, could you send beatoraja_log.xml file to us?

**Comment by Leuphorie** [comment]
I applied the beatoraja test jar and launched with the .bat. The launcher did not open. Here is the beatoraja_log.xml
https://mega.nz/#!EMJiRYpT!rmmViG4m9d7a8DQlyZqsgQByh3QOP5FY03oNGAJcDME

**Comment by exch-bms2** [comment]
This is caused by your envirionment. Check your storage(Z:) permission.

If you started test jar with your songdata.db, you can start beatoraja0.7.4 without error dialog:
there ware no logs about illegal BMSes on beatoraja_log.xml.

**Comment by Poliwrath** [comment]
> This problem occurs on your PC environment only, so that we can't help you.
Is this a translation error?
Shipping an whole computer is strange...

also...
Why is "Illegal BMS" forbidden??
If a user wants to use BM2DX convert, it should be allowed...

**Comment by produKtnz** [comment]
Dragging this issue out of the mud.
PLEASE for the love of all that is holy, pipe the "illegal BMS" finds to an output file SO WE CAN ACTUAL;LY DO SOMETHING WITH THE INFORMATION.

**Comment by 6745** [comment]
please list what illegal BMS songs are there because i get this error when updating normal tables sometimes.... this is very anti user.
