### ISSUE TITLE
a problem with sound of long notes in BMSON

### ISSUE THREAD

**Issue by excln** [exch-bms2/beatoraja#5]
- When playing a bmson, the sound of a LN is cut off at its end (of LN) although it should continue. This problem doesn't occur in an ordinary bms.
---
- bmsonプレイ時に、LNの音が（LNより長いにもかかわらず）LN終端で途切れてしまいます。この問題は通常のbmsでは起こらないようです。

**Comment by exch-bms2** [comment]
This problem may be fixed on 0.3.4.
