### ISSUE TITLE
Can't change resolution 

### ISSUE THREAD

**Issue by Agrrox** [exch-bms2/beatoraja#50]
![screen shot 2017-06-10 at 15 53 57](https://user-images.githubusercontent.com/10901821/27003349-100eb4ce-4df5-11e7-9240-0de1a0a4b337.png)

This problem happens on release 0.4.1 and also on latest builds from repository till now.
Its possible to get HD resolution by editing config.json. There is missing FHD and UHD option that was available before.
<details>
  <summary><ins>System Specs</ins></summary>
<p><b>Computer:</b> Macbook Pro 17-inch 2009 Late</p><p><b>CPU:</b> 3,06 GHz Intel Core 2 Duo</p><p><b>GPU:</b> NVIDIA GeForce 9600M GT 512 MB</p><p><b>RAM:</b> 8GB 1067 MHz DDR3</p><p><b>Internal storage:</b> SSD Samsung Pro 480GB</p><p><b>OS:</b> 10.12.5 macOS Sierra</p><p><b>Native Resolution:</b> 1920x1200</p>
</details>
<details>
  <summary><ins>BMS storage details</ins></summary>
<p><b>Storage:</b> LaCie Rugged All-Terrain 500 GB FireWire 800/ FireWire 400/USB 2.0 Portable External HDD</p><p><b>Format:</b> NTFS</p><p><b>Capacity:</b> 500 GB</p><p><b>Total of BMS data:</b> 421 GB</p><p><b>Structure of BMS Directory:</b> root/BMS/event group/event/song/data</p>
</details>
<details>
  <summary><ins>beatoraja settings</ins></summary>
<p><b>beatoraja Resolution:</b> 1280x720</p>
<p><b>Fullscreen:</b> off</p>
<p><b>Audio :</b>OpenAL</p>
<p><b>HI-SPEED fix:</b> MAX BPM</p>
<p><b>Playskin:</b> WMIX_HD</p>
</details>

**Comment by exch-bms2** [comment]
In 0.4.1, Resolution shows all available full-screen resolutions on your display. In the case of my MacBookAir, shows SD, HD and FWXGA. Could you tell me all available full-screen resolutions on your mac?

**Comment by Agrrox** [comment]
I see the following when I go to System Preferences and chose "Scaled" instead of "Default for Display"

System Preferences -> Displays -> Resolution: Scaled 
1920 x 1200
1680 x 1050
1344 x 840
1280 x 800
1152 x 720
1024 x 640

**Comment by exch-bms2** [comment]
Now I add several Resolution on branch release0.4.2 (not master). Maybe you can select 1680 x 1050 and 1920 x 1200, try it.

**Comment by Agrrox** [comment]
Tried it. Getting the following:
![screen shot 2017-06-12 at 19 51 05](https://user-images.githubusercontent.com/10901821/27047511-ac0a4f14-4fa8-11e7-85a7-7549b9a51864.png)
