### ISSUE TITLE
[0.4.1] beat-5k charts with scratches get skipped

### ISSUE THREAD

**Issue by TomoAlien** [exch-bms2/beatoraja#51]
BMSON charts that contain scratches with mode_hint set to beat-5k get skipped from being added to the database with following error message:

> D:\Gry\beatoraja_fresh>java -Xms1g -Xmx4g -jar beatoraja.jar -c
> cze 11, 2017 4:50:14 PM bms.player.beatoraja.PlayConfigurationView loadBMS
> INFO: song.db????
> java.lang.ArrayIndexOutOfBoundsException: 7
>         at bms.model.BMSONDecoder.decode(Unknown Source)
>         at bms.model.BMSONDecoder.decode(Unknown Source)
>         at bms.player.beatoraja.song.SQLiteSongDatabaseAccessor$BMSFolderThread.
> run(Unknown Source)
> cze 11, 2017 4:50:14 PM bms.player.beatoraja.song.SQLiteSongDatabaseAccessor$Son
> gDatabaseUpdater updateSongDatas
> INFO: ?????? : Time - 204 1??????? - 204
> cze 11, 2017 4:50:14 PM bms.player.beatoraja.PlayConfigurationView loadBMS
> INFO: song.db????

Charts that don't have scratches don't exhibit this problem. This bug does not happen in version 0.4.

I've included a .zip file that contains 2 5-key BMSON charts with mode_hint set to beat-5k, one of which has a scratch note in it, and one doesn't.
You can download it here:
[beatoraja_5k_bug.zip](https://github.com/exch-bms2/beatoraja/files/1066513/beatoraja_5k_bug.zip)

**Comment by exch-bms2** [comment]
I'd misunderstood that beat-5k scratch key is 6 (and also beat-10k scratch keys are 6 and 12). BMSON specification said key assign for each mode_hint. http://bmson-spec.readthedocs.io/en/master/doc/#appendices
It will be fixed on 0.4.2.
