### ISSUE TITLE
Feature request: Press Start + Select button to quit song

### ISSUE THREAD

**Issue by Agrrox** [exch-bms2/beatoraja#52]
In LR2 you can press Start button + Select Button to quit song. This is convenient shortcut for controller users, so they don't have to reach for keyboard. Please correct me if there better solution for this.

**Comment by exch-bms2** [comment]
What do you think about quitting song with wrong operation? (ex. when showing/hiding lane cover,you might touch select button by mistake)

**Comment by Agrrox** [comment]
I'm sorry the title was missleading so i updated it. I meant start + select which its Q+W by default.

**Comment by Agrrox** [comment]
Do people hide/adjust cover that much?

This shortcut was implemented in LR2 to make game completely operable using only controller. To solve accidental pressing, let there be a short time buffer after both keys presses are executed.  Lets say 1 second before it fails a song.

**Comment by exch-bms2** [comment]
I'll leave this feature up to you.
