### ISSUE TITLE
IR ClearRate Caluclation

### ISSUE THREAD

**Issue by Thulium6969** [exch-bms2/beatoraja#523]
IR Clear Rate is strange at the following condition.
*Version : beatoraja0.7.7
*Skin : csv skin
*Used skin command : #SRC_NUMBER num227 and other(212, 214, 216...etc)
*situation
First, 5sec wait and receive IR info, it shows correctly.
IR info received again after 600sec, IR clear rate is increase and sometimes become over 100%.
When receive IR info again, it seems that Total Player Count is same, but Player Count of Each Clearmark inclease.
It may be caused from not initialize Player Count of Each Clearmark.
(player count of each clear lamp add to previous its count ).
I kindly ask to confirm & modify.

**Comment by exch-bms2** [comment]
already fixed by 5c82c3d13ccc6c76f1edc1b4685b2f01329b23db

**Comment by Thulium6969** [comment]
Thank you for prompt fix.
