### ISSUE TITLE
score.db corruption when importing scores from IR

### ISSUE THREAD

**Issue by katandps** [exch-bms2/beatoraja#527]
beatorajaのクリアデータが壊れてしまったという方のscore.dbファイルをdumpしたところ、primary keyであるはずのsha256とmodeに重複のあるレコードが見つかりました。
重複レコードをdumpファイルから手動で削除し、dbファイルを復元したところ直ったという報告を受けました。

提供されたscore.dbを `sqlite3 score.db .dump > dump` で吐き出したもの
https://gist.github.com/katandps/8c966b5e62a423716d78b4944eb1e945#file-gistfile1-txt-L1851
https://gist.github.com/katandps/8c966b5e62a423716d78b4944eb1e945#file-gistfile1-txt-L1853

重複レコードについて、scorehashがmochaであるものが含まれているので、スコアインポート絡みの不具合ではないかと考えられます。
Mocha-IRからのスコアインポートを行ったのはバージョン0.7.6とのことです。また、データベースの破壊も0.7.6から起こっていたようです。

データ提供主: twitter: IIDXOHNO

**Comment by exch-bms2** [comment]
当環境では発生しませんでした。

スコアインポート周りのコードを見直した限りでは特に問題は見受けられず、
sqlite-jdbc側、もしくは環境依存でDBが破損したと考えられます。

スコアインポート処理は以下の場所になります。ご確認下さい:
https://github.com/exch-bms2/beatoraja/blob/36e6904c86a71e715c0831caf6423f5834d57b2b/src/bms/player/beatoraja/external/ScoreDataImporter.java#L62-L83
