### ISSUE TITLE
ASIO support for beatoraja in linux environments

### ISSUE THREAD

**Issue by parataxia** [exch-bms2/beatoraja#53]
Looks like ASIO + Beatoraja doesn't work in Linux environments, of course jasiohost32/64 does NOT function in linux as the wrapper is intended only for Windows' systems. Is targeted support for ASIO + Linux + Java possible? I can't find any documentation on this however, and still unsure  whether an ASIO SDK for Java is available or if it comes shipped as native vendor support... 

[Take a peak here. **sound.properties** file which changes audio service of given Java environment in Linux.](https://www.apt-browse.org/browse/ubuntu/xenial/main/i386/openjdk-8-jre-headless/8u77-b03-3ubuntu3/file/etc/java-8-openjdk/sound.properties)

btw: I have a USB soundcard now and roundtrip latency is kind of terrible using PulseAudio as default audio service in Java. :(

**Comment by exch-bms2** [comment]
As far as I know, ASIO driver for Linux doesn't exist. MacOS has CoreAudio, low-latency audio driver.

**Comment by parataxia** [comment]
Yeah I figured it out mostly on my own now, switched to Linux Mint XFCE4 and disabled *all* compositing features, significantly better frame rate now and improved audio trip latency... also, arch linux offers an asio package which confused me as I believed it was related to audio but it's in fact a low-level C++ library for various routines. The only alternative is **wineasio** (an ASIO driver for wine), but probably worthless given how much low latency most of the linux kernel is designed to be, along with MacOS. 

I'll close this for now.
