### ISSUE TITLE
[MacOS] game not launching

### ISSUE THREAD

**Issue by rullinoiz** [exch-bms2/beatoraja#530]
``
Error: Could not find or load main class bms.player.beatoraja.MainLoader
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
``

I have installed the latest version of java, the JavaSDK, and I have JavaFX installed. What could be the problem?

**Comment by evanmIS2** [comment]
Ran into the same issue. Here are my steps, more verbose for folks who haven't downloaded JavaFX yet:
* Download JavaFX Mac OS X SDK from https://gluonhq.com/products/javafx/
* Unzip to desired location (~/Downloads is fine)
* In beatoraja-confg.command replace the last line starting with `exec` the following two lines (updating the javafx-sdk version path to the one you downloaded)
`export PATH_TO_FX=~/Downloads/javafx-sdk-11.0.2/lib/
exec java --module-path $PATH_TO_FX --add-modules javafx.controls,javafx.fxml -Xms1g -Xmx4g -cp beatoraja.jar:ir/* bms.player.beatoraja.MainLoader`

**Comment by rullinoiz** [comment]
> Ran into the same issue. Here are my steps, more verbose for folks who haven't downloaded JavaFX yet:
> 
> * Download JavaFX Mac OS X SDK from https://gluonhq.com/products/javafx/
> * Unzip to desired location (~/Downloads is fine)
> * In beatoraja-confg.command replace the last line starting with `exec` the following two lines (updating the javafx-sdk version path to the one you downloaded)
>   `export PATH_TO_FX=~/Downloads/javafx-sdk-11.0.2/lib/ exec java --module-path $PATH_TO_FX --add-modules javafx.controls,javafx.fxml -Xms1g -Xmx4g -cp beatoraja.jar:ir/* bms.player.beatoraja.MainLoader`
> 
> ~_Edit_ After working with this a bit more beatoraja will run but crashes when you click play after adding BMS resources, throwing `Cannot load com.sun.java.swing.plaf.gtk.GTKLookAndFeel`. I tried swapping that value in the `beatoraja-confg.command` to `com.sun.java.swing.plaf.mac.MacLookAndFeel` but same error, `Cannot load com.sun.java.swing.plaf.mac.MacLookAndFeel`. I'm still looking into this.~
> Turns out my BMS files were bad. Using a known working BMS file like http://yaruki0.sakura.ne.jp/event/ondanyugi5/impression.cgi?no=45 works flawlessly.

seems to have worked. thanks!
