### ISSUE TITLE
Chart Playback issues on a certain chart using a certain feature in charting.

### ISSUE THREAD

**Issue by ToshiyukiDoma** [exch-bms2/beatoraja#537]
Not really a big one but there's an issue playing the chart GLITCH SWITCH [GIMMICK]. The chart uses Negavite and Positive STOPS for the BPM changes. No issues with other charts like Deal Soul, 3rd Avenue.

![image](https://user-images.githubusercontent.com/23119677/84176132-8d04ee80-aab3-11ea-93ad-5d3cdcc6e7c1.png)

**Comment by wcko87** [comment]
This issue is specifically with negative STOPs.
beatoraja currently does not treat negative STOPs the same way LR2 does.

**Comment by SackMagiclight** [comment]
The implementation of the #STOP sequence differs depending on the main unit.

The specification is as follows, but I personally think that negative numbers and floating point numbers should not be accepted. (I agree with the author of the page)

> 1/4 note of whole note in 4/4 time signature
http://hitkey.bms.ms/cmdsJP.htm#STOPXX
