### ISSUE TITLE
Some bugs on saving scores in beatoraja-0.7.8

### ISSUE THREAD

**Issue by MurasameChan** [exch-bms2/beatoraja#542]
I really enjoy this game, but I've encountered the following issues:
1. When I played the Insane 6th dan with normal gauge, in the score screen, it displayed A-Clear(Assist Easy Clear).
2. After 1, I went back to the song select screen, and the old score was not replaced by the score I just achieved.

Select Song Screen
![20200630_184705_Music_Select](https://user-images.githubusercontent.com/37019583/86122502-885bb500-bb0a-11ea-9064-4c02476ab882.png)
Settings I have used to play the dan
![20200630_184731_Music_Select](https://user-images.githubusercontent.com/37019583/86122531-91e51d00-bb0a-11ea-95e5-cc72d3ee5613.png)
Score result screen
![20200630_184618_発狂六段 LIGHT ASSIST EASY CLEAR AA](https://user-images.githubusercontent.com/37019583/86122485-8265d400-bb0a-11ea-8bef-b4c70d3ca406.png)
My IR profile which does not show the last song of Insane 6th dan(ねぇ？メイドさんはみんな忠実だと思う？ [SABOTHER7])
![Annotation 2020-06-30 200042](https://user-images.githubusercontent.com/37019583/86123617-68c58c00-bb0c-11ea-90e2-cf06438094a9.jpg)

I have also tried some songs that were in the same situation as above.

Blink[SP ANOTHER]

![20200630_160810_▽10 Blink SP ANOTHER  LIGHT ASSIST EASY CLEAR AAA](https://user-images.githubusercontent.com/37019583/86125015-927fb280-bb0e-11ea-8024-8feb5235225b.png)
![20200630_201521_Music_Select](https://user-images.githubusercontent.com/37019583/86125034-9a3f5700-bb0e-11ea-85ab-b44b2b1a27a5.png)

風仁雷仁(Another)

![20200630_161826_▽11+ 風仁雷仁(Another) LIGHT ASSIST EASY CLEAR AAA - 複製](https://user-images.githubusercontent.com/37019583/86125223-decaf280-bb0e-11ea-9a04-63569c7b8d05.png)
![20200630_201547_Music_Select](https://user-images.githubusercontent.com/37019583/86125086-ab886380-bb0e-11ea-8a42-3a771aff19b0.png)

**Comment by exch-bms2** [comment]
I think you enable some assist options (Maybe BPM-Guide or Constant). Check your assist options.

**Comment by MurasameChan** [comment]
![image](https://user-images.githubusercontent.com/37019583/86202075-d8328e80-bb93-11ea-81b9-8fc90f3c915a.png)
Didn't know bpm guide is enabled by default lol
