### ISSUE TITLE
[Discuss] Batch sync offline scores and lamp

### ISSUE THREAD

**Issue by shellqiqi** [exch-bms2/beatoraja#545]
I have many offline scores. Then I notice that Beatoraja only upload the score and lamp when complete ONE song. So is there any possible to sync scores and lamps before entering the game? Like a upload button and a fetch button on the configuration window.

**Comment by shellqiqi** [comment]
I have worked out a version of IR scores batch uploading. Please check [here](https://github.com/shellqiqi/beatoraja/releases/tag/alpha).

It is an experimental modification. Please read the release carefully.

@exch-bms2

**Comment by exch-bms2** [comment]
Offline scores are not protected from score modification by external application.
So that sending offline scores breaks soundness of IR. If you publish IR API hacks,  IR will be not trusted by user.
You should recognize this.

**Comment by shellqiqi** [comment]
OK I removed the branch and release.

In addition, can users upload their offline scores in private field which not participate in global ranking but rival can get?
Or beatoraja can import other's score database as offline rival?
