### ISSUE TITLE
bug report: Doesn't save a song result.

### ISSUE THREAD

**Issue by takahiro-saeki** [exch-bms2/beatoraja#550]
## 問題
beatoraja0.7.9を使用していて特定の楽曲のスコアが保存されない現象が起きています。ただ何故特定の楽曲で起こっているのかは不明です。issueを一通り見ましたが見落としていない限りでは同様の現象が見られなかったので質問の意味も込めてissue立てました。

スコアが保存されない楽曲一例
Halcyon[HYPER]
https://mocha-repository.info/song.php?sha256=88deededb31997c443d5cf53b010af6bf0009531259d57a5b065795d1e8d6695

suffruti
https://mocha-repository.info/song.php?sha256=4465a0de83c24befd26c54ddf0e57c5b94f241813f7dac8e740da3699c1f16ea

ググったのですが、楽曲が保存されない事があるというケースは無さそうだったので対策などあれば教えて欲しいです。

**Comment by Shimi9999** [comment]
どちらもBPM変化がある曲なので、アシストオプションのBMPガイドかコンスタントがONになっているのが原因だと思われます。
関連Issue: #542

**Comment by takahiro-saeki** [comment]
@Shimi9999 ありがとうございます！！直りました！！
とても早い返信、ありがとうございました！！！
