### ISSUE TITLE
ReplayDara is saved without PaternModifyLog in a particular situation

### ISSUE THREAD

**Issue by djestelle** [exch-bms2/beatoraja#56]
1. When I play with random option, I can restart with the same note as before by pressing white key and black key at the same time. Sometimes, that doesn't do right as they show the original note.

2. When I play it once again with random option by pressing white key and black key at the same time, and turned it off and on, then the replay do weird because note that I press does not match with the note that I can see.
Example video : https://youtu.be/-j_cBnyjYes
This video is from beatoraja 0.4.2

**Comment by exch-bms2** [comment]
I can't understand this situation accurately, so please explain more information about it to me.
Which state did it occur? (ex. transiting from Result to Play)
and what keys did you pressed? (ex. 1 and 2 key)

**Comment by djestelle** [comment]
1. I pressed 6 key + 7 key.
It happened at transiting from result to play.

2. Result -> pressed 6key+7key -> restarted the song -> easy cleared it -> then restarted beatoraja to capture video -> tried to replay it -> then the example video-like situation happened.

**Comment by exch-bms2** [comment]
I see. Would you upload this replay data? Replay data exists at (beatoraja)/replay/(SHA-256 of Dream Rocket Reaju).brd.

**Comment by djestelle** [comment]
Here is the replay file.
[replay data.zip](https://github.com/exch-bms2/beatoraja/files/1128280/replay.data.zip)
