### ISSUE TITLE
Beatoraja crashes whenever I hit AutoPlay

### ISSUE THREAD

**Issue by WintermintP** [exch-bms2/beatoraja#585]
Hi... Hi... Hi...

Noob question, I know, but I'm having trouble trying to activate AutoPlay on Beatoraja. This is actually painful for me, because I need AutoPlay to get a better idea of how my future charts are going when I get to them. I play guitar in a band and we already have nine albums released, and I've been wanting to add my own songs into the game and then publish it for everyone else to try. I already attempted this on StepF2 but the community there hasn't been helpful.

Is there anything I could try?

**Comment by WintermintP** [comment]
Before you say anything, I have yet to figure out what the hotkeys menu means by "KEY 5" and I don't have a IIDX controller yet, which I'm already looking into buying one.

**Comment by WintermintP** [comment]
Okay, I found some more problems with the game, even if I were to attempt to play a song normally the song won't load and the game crashes...

**Comment by wcko87** [comment]
I suggest using this guide as a starting point.
https://github.com/wcko87/beatoraja-english-guide/wiki

**Comment by WintermintP** [comment]
I already have, no dice on that either.

**Comment by WintermintP** [comment]
They did mention SabunHelper but I have no clue how to run that thing...

**Comment by wcko87** [comment]
To be more specific, look under the section about the locale fix. If you are experiencing frequent crashes in beatoraja, it is highly likely that that is the cause.

If you are thinking about composing music for BMS, I suggest looking through the BMS Overview and Making Charts section for an understanding of how the community works and how making music for BMS works.

**Comment by WintermintP** [comment]
@wcko87 Somebody did mention something about Locale and UTF-8 enabling, which I have done correctly, but it keeps saying there's something missing that doesn't allow UTF-8 support, so that can't be it either.

**Comment by wcko87** [comment]
what is the specific error you are receiving with UTF-8?

**Comment by WintermintP** [comment]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

**Comment by WintermintP** [comment]
I have Japanese installed on my computer by the way.

**Comment by wcko87** [comment]
> F4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

I believe this error doesn't have anything to do with UTF-8, and does not cause any issues if it happens.

Japanese locale is not needed if you have applied the UTF-8 fix correctly.

**Comment by WintermintP** [comment]
Sorry about the delay. I was in the middle of a phone call.

Would it be okay if you could wait a bit of a while so I can figure out the instructions? They kind of were a bit vague so I'm going to go over them to see if I missed anything. Thank you.

**Comment by WintermintP** [comment]
![image](https://user-images.githubusercontent.com/77370648/104628541-59e89600-5666-11eb-9e3e-81df2379fba9.png)
Did I mess up...?

**Comment by wcko87** [comment]
That looks correct, and do you run beatoraja through the bat file?

When does the crash occur? is it immediately after starting a song or immediately after the decide screen (splash screen as a song starts) finishes?
Because the other possible cause is the DECIDE or PLAY skins not being properly configured.

**Comment by WintermintP** [comment]
The crash happens as soon as I hit any one of the PLAY buttons. The song doesn't even start. I'm still stuck on the song select bgm and it just... yea...

**Comment by WintermintP** [comment]
I think the DECIDE/PLAY not being properly configured might be the reason. Does the guide cover how to fix that?

**Comment by wcko87** [comment]
Go into the skin settings and make sure all the important skin categories have been set. This is especially important if you had cleared out your player config json earlier to reset your settings.
reference: https://github.com/wcko87/beatoraja-english-guide/wiki/Configuration#skin-settings

Anyway, in future please don't use the issue tracker for troubleshooting or tech support. That's not what the github issue tracker is for.

**Comment by WintermintP** [comment]
Then where do I go to for troubleshooting...?

**Comment by wcko87** [comment]
Not here. We don't provide tech support because this is just an open source project.
If you are looking for help, you can ask people on the BMS community discord or maybe contact me directly via discord or twitter.

**Comment by WintermintP** [comment]
My Discord is WintermintP#8999

**Comment by WintermintP** [comment]
And I've been unable to find the BMS community.

**Comment by wcko87** [comment]
google "bms community discord", first result

**Comment by wcko87** [comment]
@exch-bms2 please close
