### ISSUE TITLE
Autoplay misses in certain BMSes

### ISSUE THREAD

**Issue by hanubeki** [exch-bms2/beatoraja#6]
Autoplay doesn't play some notes in certain BMSes.

Affected BMSes
* Lots Of Spices[lots mineds]
* Engine [EXPLODE]
* L9999999999999^99999999999

**Comment by exch-bms2** [comment]
This problem has been fixed in 138164eb05b94030ee86744b2bdeadf86ac36a1a, and confirmed auto-playing Lots Of Spices and Engine correctly.

**Comment by hanubeki** [comment]
Notes is flickering in L9999999999999^99999999999 but that is another issue, this can be closed.
