### ISSUE TITLE
Cannot save setting in configuration

### ISSUE THREAD

**Issue by LuvPiano** [exch-bms2/beatoraja#607]
All settings were changed to default every time it starts, including user name, play option and skin settings. I must set them every time when opening the program.

**Comment by rekidai-info** [comment]
@LuvPiano 
I haven't seen beatoraja's implementation, so I'm just guessing, but I think a common problem is permissions.
I don't think there are many programs that reference/change ACLs(https://docs.microsoft.com/en-us/windows/win32/secauthz/access-control-lists) or read-only property when making changes to files.
Is the beatoraja folder protected (e.g. Program Files is under)?
The quickest way to troubleshoot this is to run beatoraja-config.bat with administrative privileges.
I haven't seen beatoraja's implementation, so I'm just guessing, but I think a common problem is permissions.

**Comment by fnmdx111** [comment]
It's also possible that you are using a different locale than the one that's used by default by beatoraja. Read https://github.com/wcko87/beatoraja-english-guide/wiki#locale-fix for more info.
