### ISSUE TITLE
Use 7key playskin to play 5key charts with disable lane cover.

### ISSUE THREAD

**Issue by Agrrox** [exch-bms2/beatoraja#62]
There are so few 5key playskins and none of those are HD.
In LR2 there is function that let you use use 7key playskin to play 5key, by adding disable lane cover to the right two lanes. 
This would be cool feature, because you can then use WMIX_HD or Endless Circulation skins to play 5key.

![screen shot 2017-07-23 at 18 21 23](https://user-images.githubusercontent.com/10901821/28501066-2ba5a034-6fd4-11e7-8193-8d65511342e2.png)

**Comment by exch-bms2** [comment]
You need to consider where you bring "Disable Lane" image from. If in skin image files, how to detect this image?

**Comment by Agrrox** [comment]
WMIX_HD: uses sprite cover from /WMIX_HD/system/frame.png
ECSE: uses sprite cover from /EndlessCirculation/Play/_parts/parts.png

I think there is some parameter in .csv that define this function.

**Comment by exch-bms2** [comment]
Do you tell me dst_option ID when disabling 6-7 lane?

**Comment by exch-bms2** [comment]
Do you get ECSE skin developer's permission to redistribute this? If not, you must to delete this.

**Comment by Agrrox** [comment]
in ECSE i found this:
`//レーンカバー (161 5keys時のみ`
