### ISSUE TITLE
beatoraja crashes when it tries to display certain Machine-dependent character 

### ISSUE THREAD

**Issue by sr8e** [exch-bms2/beatoraja#621]
body: beatoraja0.8.2
skin: LITONE6

beatoraja crashes when it tries to display certain machine-dependent character such as ㌍㌢ ,
it might be caused by bitmap font.

**Comment by asesidaa** [comment]
You can try bump the version of libgdx (and other dependencies), and see if that fix the issue.

**Comment by sr8e** [comment]
it works fine in beatoraja 0.8.6 of JRE-bundled executable version.
