### ISSUE TITLE
[Request] If an image or video is undefined, automatically load a BGA with a specific file name

### ISSUE THREAD

**Issue by tasmaniandevil1** [exch-bms2/beatoraja#622]
I have a BMS with an undefined BGA.
If the BGA has uploaded later, I cannot edit BMS to prevent the hash value from changing.
So, I would like it to load images and videos when they are placed with a specific file name.
This feature has already been implemented in the preview sound source.

私の持っているBMSにはBGAの定義がないものがある。
後からBGAがアップロードされても、ハッシュ値が変わることを防ぐためにBMSは編集できないです。
だから、特定のファイル名で画像や動画が置かれていたら読み込むようにしてほしいです。
これはプレビュー楽曲では実装済みの機能です。

**Comment by exch-bms2** [comment]
BMS with an undefined BGA have no BGA start timing definition.
So I think this method can't solve the problems about synchronizing between music and BGA.
