### ISSUE TITLE
Error: Could not find or load main class bms.player.beatoraja.MainLoader

### ISSUE THREAD

**Issue by kxrider** [exch-bms2/beatoraja#627]
This is the error I get when I run beatoraja-config.bat in Windows. This issue has been raised before, but the solutions have not worked for me or were OS specific. So far, I have installed Java 8, and when that did not work, I installed Liberica JDK 8, which is also supposed to come with JavaFX, but I am getting the same error. Here is my beatoraja-config.bat file: https://pastebin.com/j2LpdtvD. So far, all I have done to it is apply the Locale fix.

**Comment by hadronyche** [comment]
What version of beatoraja are you using? Do you have a beatoraja.jar present? It sounds like you've downloaded the source code zip from the releases page, instead you should follow the link on the same page (https://mocha-repository.info/download.php). The first link on that page (beatoraja-0.8.2-jre-win64) comes with Liberica JRE bundled and should work standalone.

**Comment by kxrider** [comment]
I did not download the source code (I have made that mistake before on a different PC!). I have the version in the second download link (beatoraja-0.8.2-modernchic). I also downloaded beatoraja-0.8.2-jre-win64, but it doesn't come with a bat file to start the jar, so I am not sure what to do. If try to use the same .bat file from beatoraja-0.8.2-modernchic to start the jre-win64 version, I get the exact same error.

I can run the .exe just fine, but the Beatoraja english guide makes it sound as if the corresponding locale fix is less robust than the fix for the java version, so I have been avoiding that.

**Comment by wcko87** [comment]
Please read this
https://github.com/wcko87/beatoraja-english-guide/wiki#4-error-could-not-find-or-load-main-class-bmsplayerbeatorajamainloader

**Comment by kxrider** [comment]
> This is a missing javafx issue.
> Please read this:
> https://github.com/wcko87/beatoraja-english-guide/wiki#4-error-could-not-find-or-load-main-class-bmsplayerbeatorajamainloader
> 
> Please use the discussions tab on the beatoraja english guide for troubleshooting help, rather than this issue tracker.

I have read this and already tried their suggestions. See my original post where I have followed the steps to download Java 8 and Liberica JDK in attempt to fix this. I am saying these things have not worked. I can close this if you think it is truly unfit, but I asked here since issues involving this error have been raised here 5 times before (and their solutions did not help).

**Comment by wcko87** [comment]
I'll help you out, make a post in the discussions page and close this issue.

**Comment by kxrider** [comment]
Alright. https://github.com/wcko87/beatoraja-english-guide/discussions/35
