### ISSUE TITLE
beatoraja icons

### ISSUE THREAD

**Issue by Agrrox** [exch-bms2/beatoraja#63]
I tried to make some logo for beatoraja. Not sure if it looks good, but i will just leave it here. 
Also is there some documentation for making Theme for beatoraja?
![beatoraja_logo-14](https://user-images.githubusercontent.com/10901821/28502722-dbc171f4-6ff8-11e7-95d0-2ef85800b68d.jpg)

**Comment by Agrrox** [comment]
Issue closed because of not being a priority.

**Comment by UlyssesZh** [comment]
![Image](https://github.com/user-attachments/assets/69dc4487-19a2-420c-bbca-ceb606c02c02)

I created an SVG logo based on your creation.
