### ISSUE TITLE
About JUDGE AUTO ADJUST

### ISSUE THREAD

**Issue by MiraiScarlet** [exch-bms2/beatoraja#637]
jp:判定自動調整機能について

discord BMS Server discussion
https://discord.com/channels/415146687674449921/416372895275679755/814168978196529162

上記で上がった懸念点など
・「プレイ中にリアルタイムで判定調整させる」(=LR2と同一仕様)はゲーム性を崩壊させてないか
→競技性に問題はないか
・↑で使用するにしてもアシスト扱いにしスコアは記録させないとかはできる
→LR2では記録されるが、[考慮漏れの可能性がある](https://discord.com/channels/415146687674449921/416372895275679755/814171607542792254)
・プレイ中には変更せず、リザルトで自動反映させてもいいのではないか
・自動調整はそもそも曲ごと音切りの具合でずれまくるので統一することができない

当Issueは、実装に向けての議論の場所に使用してください。

============================================================
Translate to English(by DeepL)

Concerns raised above

・Doesn't the "real-time judgment adjustment during play" (same specification as LR2) destroy the gameplay?
→Is there a problem with the competitiveness?
・It is recorded in LR2, but there is a possibility that it is not taken into account (https://discord.com/channels/415146687674449921/416372895275679755/814171607542792254).
・It is possible that the score is not recorded in LR2, but it may not be taken into account.
・It's not possible to unify the auto-adjustment because it varies from song to song depending on the sound cut.

Please use this Issue as a place to discuss the implementation of JUDGE AUTO ADJUST.

**Comment by katandps** [comment]
## 意見
beatorajaはリザルトで表示される判定のデータが多いため、手動で精度のよい判定調整ができます。
自動調整結果をリザルトで反映する場合はあまり意味がない機能になりそうです。

LR2と同等の自動判定調節機能については、その機能がない場合に比べてスコアを高めやすい/クリアしやすい譜面が存在します。そのため調整機能をONにしてプレイ、曲終了後判定をもとに戻す、といったプレイスタイルが見られます。
要するに、(アシスト扱いにしない場合は)実装の前後でスコア/クリアの価値が変動します。

実装後十分に時間が経過した後は単に数あるオプションの一つとして受け入れられると考えていますが、
突き詰めたプレイをする際に、LR2と同様に調整機能ON+判定を手動で調整するプレイが最良の選択になるのは面倒なのであまりうれしくないです。

自動調整ONの場合は スコア/クリアともに保存しない とするか、
自動調整ON / OFF / FIX(曲終了後もとに戻す) のような構成になるとうれしいです。

## 備考
IIDX29のロケテが行われており曲途中での自動判定調整機能が新機能として記載されているようです。
無関係なゲームではありますが、競技性の価値観はこちらの実装に影響されていくものと思われます。

**Comment by exch-bms2** [comment]
beatoraja 0.8.4 will include the Notes Display Timing Auto Adjusting feature (old name : Judge Auto Adjust).
