### ISSUE TITLE
GPL violation of user freedom

### ISSUE THREAD

**Issue by nogomr** [exch-bms2/beatoraja#647]
Restricting access to "illegal" BMS files is a direct violation of the GPL user freedoms, as the GPL clearly states that the user has the freedom to use the software **for any purpose,** among other things.

**Comment by SackMagiclight** [comment]
The GPL is the copyright and terms of use for the source code, and does not apply to the authors themselves.
You have the right to fork and modify the source code under the GPL license.

**Comment by wcko87** [comment]
It is not a GPL violation.
