### ISSUE TITLE
Problem about running on openJDK : Could not find or load main class bms.player.beatoraja.MainLoader

### ISSUE THREAD

**Issue by lukeoftheaura** [exch-bms2/beatoraja#67]
When I start beatoraja with the command `java -jar beatoraja.jar ./bms`, I get the following error:
```
Error: Could not find or load main class bms.player.beatoraja.MainLoader
```
I'm using the latest release, on 64-bit arch linux.

**Comment by exch-bms2** [comment]
You need to install openJFX if using openJDK.

**Comment by lukeoftheaura** [comment]
installed openJFX, now it's saying it can't find openAL.

**Comment by exch-bms2** [comment]
> java -jar beatoraja.jar ./bms

What is "./bms"? [BMS Path] must be BMS file.

**Comment by lukeoftheaura** [comment]
ah, I thought that was the path to the directory the files were stored in, my bad.

**Comment by exch-bms2** [comment]
That's good. If you want to start configuration, use -c option. [BMS Path] is the API for playing specified BMS directly.

**Comment by lukeoftheaura** [comment]
config's all in japanese, and I can't read that. Is there a way to specify english?

**Comment by exch-bms2** [comment]
Sorry, now default language is ja-JP. use this command:

> java -Duser.language=en -Duser.country=US -jar beatoraja.jar -c

I'll set defalut language to english sometimes soon.

**Comment by lukeoftheaura** [comment]
OK, now the game will start, but whenever I try to start a song, I get the error:
```
Exception in thread "LWJGL Application" java.lang.NullPointerException
	at bms.player.beatoraja.play.BMSPlayer.create(Unknown Source)
	at bms.player.beatoraja.MainController.changeState(Unknown Source)
	at bms.player.beatoraja.decide.MusicDecide.render(Unknown Source)
	at bms.player.beatoraja.MainController.render(Unknown Source)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)
```

**Comment by exch-bms2** [comment]
Please create an another issue.
