### ISSUE TITLE
アナログスクロール感度の不具合

### ISSUE THREAD

**Issue by qoin2267** [exch-bms2/beatoraja#683]
beatorajaの起動時、「選曲」タブ→「アナログスクロール感度」の設定が選曲スクロールだけでなく楽曲プレー時のアナログスクラッチの反応にも影響しているようです。
例：DAO FPS INFINITASモードでアナログスクラッチを有効にしてプレーした場合、「アナログスクロール感度」が3だとターンテーブルを10°程のスピンで反応、1だと3°程のスピンで反応、といった具合

アナログスクラッチの感度は選曲スクロール時用、プレー時の反応用に分けられると助かります。

**Comment by wcko87** [comment]
「アナログスクロール感度」の設定は楽曲中のアナログスクラッチには影響していません。（選曲のみ）
3でも100でも同じです

**Comment by SackMagiclight** [comment]
[コードの通り](https://github.com/exch-bms2/beatoraja/blob/5eb8df73b0a1e7dfc0f3f25e908f5a710f620cb7/src/bms/player/beatoraja/select/MusicSelectInputProcessor.java#L166)、「選曲」の「アナログスクロールの感度」はプレーには影響していません。

DAOコン自身で感度しきい値を設定できるのでそのあたりなのかなぁと思います。  
念の為プレコンで感度10とかで試してみましたが、体感差はありませんでした。

**Comment by qoin2267** [comment]
返答遅くなってしまいすみません。
こちらの勘違いのようでしたので取り下げます、お手数おかけしました。
