### ISSUE TITLE
Unable to press start, tabs simply gray out instead

### ISSUE THREAD

**Issue by 1felys** [exch-bms2/beatoraja#696]
Hey there, I just attempted to set up beatoraja following the guide (I'm on macos for context) and when I actually hit play to start the game nothing launches, and instead every tab on the configurations menu is grayed out aside from Music Select, Skin and Table. Any crucial step I'm missing or something that would explain this?
<img width="985" alt="Screen Shot 2022-04-20 at 10 06 20 PM" src="https://user-images.githubusercontent.com/96160749/164376240-d8f75f32-ac1b-4bad-89b2-10c3588ab6a3.png">

**Comment by hadronyche** [comment]
The greyed out tabs are intended when the game starts.

Are you able to run it through a command line (e.g. with the batch file [here](https://github.com/wcko87/beatoraja-english-guide/tree/resources/beatoraja-configs-win64jre)) and see if there's a useful error there?

**Comment by 1felys** [comment]
> 
<img width="1008" alt="Screen Shot 2022-05-01 at 10 23 30 PM" src="https://user-images.githubusercontent.com/96160749/166188049-24f2e1cc-b085-4337-a840-3acd4f2f5a1a.png">
<img width="1019" alt="Screen Shot 2022-05-01 at 10 23 38 PM" src="https://user-images.githubusercontent.com/96160749/166188061-7b296932-c08d-4f41-9b73-0280dad876df.png">
<img width="982" alt="Screen Shot 2022-05-01 at 10 23 42 PM" src="https://user-images.githubusercontent.com/96160749/166188062-ed716596-5377-4146-813c-1e92683b45f1.png">

here you are !

**Comment by superryan14** [comment]
Similar things happen with mine, I downloaded a song pack from the wiki (GENOSIDE 2018 starter pack specifically) , set up the resource to the packs folder, when I hit start, it goes not responding and nothing happens if I wait 30+minutes, not sure what I should do. The game opens up with no songs but once I try to add songs it just hangs here.
