### ISSUE TITLE
FPS limit value range more than 1000

### ISSUE THREAD

**Issue by RaceDriverMIKU** [exch-bms2/beatoraja#700]
Thesedays, there are keyboards support more than 1000Hz polling rate, such as 4000Hz, or 8000Hz.
For example, it is not about keyboard, but beatcon, if I use v-sync, so FPS is limit to 60Hz, turntable input is laggy. IO processing is tied to frame update.
Can you increase FPS limit up tp 10000 FPS? or remove limit, so make it there is no need to use nVIDIA profile inspector.

**Comment by wcko87** [comment]
set it to 0 to uncap FPS.

**Comment by RaceDriverMIKU** [comment]
I mean, it is too high if I uncap FPS limit. so I need to use rivatuner, or nvidia profile inspector.
Anyway, if it is implemented properly, in-game fps limiter performs best, so I asked it.
