### ISSUE TITLE
key configuration

### ISSUE THREAD

**Issue by lukeoftheaura** [exch-bms2/beatoraja#71]
Hi,
I know this isn't really an issue but I do not know where else to ask - how do I configure the keyboard?

**Comment by excln** [comment]
See [manual/memo](https://github.com/exch-bms2/beatoraja/blob/master/manual/memo).
Press '6' key (not numpad) in the music selection screen.

**Comment by exch-bms2** [comment]
I need to make wiki for storing misc questions and answers.
