### ISSUE TITLE
Right-clicking on the rival selector switch causes oraja to crash.

### ISSUE THREAD

**Issue by KissaRori** [exch-bms2/beatoraja#710]
https://twitter.com/KissaRori/status/1556766231947931649?s=20&t=P4Q_1kpOI58eqZsKIG6c2w

act = 79
Right-clicking on a rival selector switch causes oraja to crash. It does not crash offline.

**Comment by exch-bms2** [comment]
already fixed (see #671)

**Comment by KissaRori** [comment]
OK thank you!
