### ISSUE TITLE
[Need help] Loading from IR (mocha) costs too much time

### ISSUE THREAD

**Issue by cutekibry** [exch-bms2/beatoraja#729]
I am using Beatoraja 0.8.4 on Windows 11 and noticed that the program freezes during preloading and costs too much time (~8min). This will happen **only** when I use mocha's IR system.

There seems to be no requests in my network logs during loading, and I can use the mocha IR normally after loading (though need ~2s to get IR's state).

I have 7299 charts in total.

**Comment by rekidai-info** [comment]
開発者に再現が可能な手順なり環境なりがないと調査は難しいでしょう
それがなければ事象が起きている時点のスレッドダンプ（一定間隔で数回取得してください）を取得してどこかにアップロードすると誰かが見てくれるかもしれません
読んだ限りでは確率は低いですが、一般論としてはウイルスソフト等の他プロセスが悪さをしている可能性もあるのでOSを最小構成で起動するなりして事象が再現するかも調査してみてください
