### ISSUE TITLE
Load default sprite from .lr2skin file instead by alphabetical order.

### ISSUE THREAD

**Issue by Agrrox** [exch-bms2/beatoraja#74]
It seems beatoraja load sprites in alphabetical order. But in case LR2 skins, It should determine what is default sprite to load. 

For example beatoraja loads `budweiser.png` but it should be `default.png` because its as default in lr2skin file.

`#CUSTOMFILE,LANECOVER,.\LR2files\Theme\WMIX_HD\play\parts\lanecover\ac\*.png,default`

**Comment by nigue** [comment]
quieres t
