### ISSUE TITLE
PACEMAKERを変更できない

### ISSUE THREAD

**Issue by KobatoAtOraja** [exch-bms2/beatoraja#748]
選曲画面でオプションを開きながら上下矢印キーを押してターゲットスコアグラフを変更しようとしても「A-」から変更できず、プレー時も正しいターゲットスコアグラフが表示されない

**Comment by MiraiScarlet** [comment]
使用している本体とスキンが不明なので正確なことは言えませんが…

**0.8.5(最新版/2023.03公開)ではスコアターゲットの仕様変更が行われております。**
このため、**0.8.5に対応したスキンでないと選曲画面からターゲットスコアの変更は不可能**です。

**Comment by KobatoAtOraja** [comment]
ありがとうございます

本体は0.8.5、スキンはLITONE5を使用していたのでペースメーカー変更未対応という認識で良いでしょうか？
