### ISSUE TITLE
LUA skins won't save the skin config

### ISSUE THREAD

**Issue by Vad1mCSO2** [exch-bms2/beatoraja#751]
Some LUA skins [includes Modern Chic] won't save the config. JSON/LR2 saving config just fine

**Comment by Vad1mCSO2** [comment]
I can't run
![image](https://github.com/exch-bms2/beatoraja/assets/76803825/16d6532d-0af1-47e4-af3b-bf0e2641bf5b)

**Comment by wcko87** [comment]
See [Error: Could not find or load main class bms.player.beatoraja.MainLoader](https://github.com/wcko87/beatoraja-english-guide/wiki/FAQ-and-Troubleshooting#4-error-could-not-find-or-load-main-class-bmsplayerbeatorajamainloader)
it's a missing javafx issue. The link explains how you can fix it.

**Comment by Vad1mCSO2** [comment]
https://bell-sw.com/pages/downloads/ with full package
