### ISSUE TITLE
[FEATURE REQUEST: SKIN] Note distribution graph in portrait orientation

### ISSUE THREAD

**Issue by sr8e** [exch-bms2/beatoraja#769]
support note distribution graph (and other similar looking parts) in portrait orientation, not only landscape

ノーツ分布グラフやその他類似のパーツを、横向きだけでなく縦向きにも描画できるとスキン制作の幅が広がってよいのではないかと思います

**Comment by exch-bms2** [comment]
destinationのangle=90 or 270で縦に描画できますが、専用の数値が必要ですか？

**Comment by sr8e** [comment]
横長のオブジェクトなので、angleで回転させると配置が非直感的になりがちかと思ったのですが、あまり頻繁に需要があるわけでもないと思うので、そのままでもいいかもしれません。
