### ISSUE TITLE
Encoding problem with ./player/(PLAYER_NAME)/config.json file

### ISSUE THREAD

**Issue by FelisCatusKR** [exch-bms2/beatoraja#81]
It seems that config.json file in player folder is saved as ANSI encoding, which means unicode letters cannot be used in skin options. I think the encoding of this file should be changed to UTF-8.

**Comment by parataxia** [comment]
I believe this can be resolved by adding this environment variable to your launch script:
 
`set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 ` - Windows
  or
`export JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8` - Linux/OS X

**Comment by FelisCatusKR** [comment]
Okay, so after I studied Java by myself, I've figured out that a usage of `FileWriter` and `FileReader` causes this problem because that classes use the system encoding when its OS is Windows (which is obviously not UTF-8 in general condition.)

https://github.com/exch-bms2/beatoraja/blob/89e6ab145468461cffe1cf7a3b3a336c3c9d8dd8/src/bms/player/beatoraja/PlayerConfig.java#L894-L918

Of course, you can use such a 'UTF-8 fix', editing a batch file with an addition of an environment variable `JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8`. However, when it comes to executable binaries like the one in Mocha-Repository, we can't do that black magic.
Luckily, there are standard classes that can read/write files in specific locale, `OutputStreamWriter` and `InputStreamReader`. If these classes are used for this section, users won't need that 'UTF-8 fix' anymore.

```java
try (OutputStreamWriter writer =
    new OutputStreamWriter(new FileOutputStream(Paths.get(playerpath + "/" + player.getId() + "/config.json"), StandardCharsets.UTF_8))
) {
```

The problem is, if users who haven't used a 'UTF-8 fix' (typically users who are using Windows in Shift-JIS encoding), their configuration file will be deleted because it has not been in UTF-8 encoding so they'll loose all their configurations.

This can be solved by using an external library such as [icu4j](https://icu.unicode.org/home), but I'm not sure it is proper solution for this case. Any ideas?

(Sorry for my poor English)
