### ISSUE TITLE
Unable to launch beatoraja 0.8.7 (macOS ARM platform + Java 22)

### ISSUE THREAD

**Issue by haikuotiankong114514** [exch-bms2/beatoraja#824]
When using command `java -jar /path/to/beatoraga.jar` to launch beatoraja, the terminal always pop up an error message: 
![image](https://github.com/user-attachments/assets/c9f62da9-df25-4f2a-b106-921f067d9cf7)
which roughly means can't load blah blah blah. Tried chmod -R 755 but failed.
I'm using macOS 15 (ARM) with zulujdk Java 22, along with the latest 0.8.7 version (without modernchic). Below are the `java -version` information:
```
haikuotiankong@haikuotiankongdeMacBook-Pro ~ % java -version
openjdk version "22.0.1" 2024-04-16
OpenJDK Runtime Environment Zulu22.30+13-CA (build 22.0.1+8)
OpenJDK 64-Bit Server VM Zulu22.30+13-CA (build 22.0.1+8, mixed mode, sharing)
```
Can't find log, but if you need I'll try.

**Comment by haikuotiankong114514** [comment]
my bad. it needed the specific java 17 and i didnt know it.

**Comment by hamzah-opal-n** [comment]
Which version of Java got it working for you? I'm having trouble starting the game on Apple Silicon as well.

**Comment by haikuotiankong114514** [comment]
> Which version of Java got it working for you? I'm having trouble starting the game on Apple Silicon as well.

I don't think it's going to work on ARM macOS. This is an really old post and I was launching successfully with Liberica's Java 17 I remember, but it just won't go to the game interface, and by logs I guess it's issues related to ARM architectures, the program tried to find some x86 resources which will never exist on an ARM-based java environment, and the developers seemed to refuse to  fix this. I'm quite confused by this.
If you wish you can try a x86 copy of java17 and run it over Rosetta? I didn't try it I remember

**Comment by hamzah-opal-n** [comment]
I followed a guide on YouTube and got beatoraja to run. Unfortunately, the sounds during gameplay keep dropping or cutting out, so that's upsetting :(

**Comment by djx314** [comment]
@haikuotiankong114514 Can have a test as the Issue 834 to import JavaFX to the new version JDK.

**Comment by Hezzle** [comment]
> I followed a guide on YouTube and got beatoraja to run. Unfortunately, the sounds during gameplay keep dropping or cutting out, so that's upsetting :(

same issue lol
mine isn't even not ARM🤔
